import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

const ROOT = '';
const API = '/api';
const navGroups = [
  ['Service', ['Incidents','Requests','Problems','Changes','Knowledge']],
  ['Infrastructure', ['Sites','Server Rooms','Racks','Equipment']],
  ['Compliance', ['Audits','Inspections','Evidence']],
  ['Platform', ['Assets / CMDB','Reporting','Administration']]
];
const roles=['Administrator','Service Desk','Engineer','Infrastructure','Auditor','Read Only'];

function Badge({children, tone='blue'}) { return <span className={`badge ${tone}`}>{children}</span>; }

function App(){
  const [token,setToken]=useState(()=>localStorage.getItem('opscore_token')||'');
  const [user,setUser]=useState(null);
  const [authChecking,setAuthChecking]=useState(Boolean(token));
  const [loginError,setLoginError]=useState('');
  const [page,setPage]=useState('Dashboard');
  const [incidents,setIncidents]=useState([]);
  const [requests,setRequests]=useState([]);
  const [assets,setAssets]=useState([]);
  const [users,setUsers]=useState([]);
  const [sites,setSites]=useState([]);
  const [locations,setLocations]=useState([]);
  const [selectedSite,setSelectedSite]=useState(null);
  const [dashboard,setDashboard]=useState({incidents:0,requests:0,assets:0,users:0,sites:0,locations:0,slaBreaches:0});
  const [search,setSearch]=useState('');
  const [incidentModal,setIncidentModal]=useState(false);
  const [assetModal,setAssetModal]=useState(false);
  const [userModal,setUserModal]=useState(false);
  const [siteModal,setSiteModal]=useState(false);
  const [locationModal,setLocationModal]=useState(false);
  const [toast,setToast]=useState('');
  const [loading,setLoading]=useState(false);
  const [apiState,setApiState]=useState('Connecting');

  const notify=text=>{setToast(text);window.setTimeout(()=>setToast(''),2400);};
  const canWriteIncidents=['Administrator','Service Desk','Engineer','Infrastructure'].includes(user?.role);
  const canWriteAssets=['Administrator','Engineer','Infrastructure'].includes(user?.role);
  const canWriteSites=['Administrator','Infrastructure'].includes(user?.role);
  const isAdmin=user?.role==='Administrator';

  async function request(url,options={}){
    const headers={'Content-Type':'application/json',...(options.headers||{})};
    if(token) headers.Authorization=`Bearer ${token}`;
    const response=await fetch(url,{...options,headers});
    const body=await response.json().catch(()=>({}));
    if(response.status===401 && token){ logout(false); throw new Error('Session expired'); }
    if(!response.ok) throw new Error(body.error||`HTTP ${response.status}`);
    return body;
  }
  const json=(path,options={})=>request(`${API}${path}`,options);

  function logout(show=true){localStorage.removeItem('opscore_token');setToken('');setUser(null);setUsers([]);setSites([]);setLocations([]);setSelectedSite(null);if(show)notify('Signed out');}

  async function login(e){e.preventDefault();setLoginError('');const f=new FormData(e.currentTarget);try{const data=await request(`${ROOT}/auth/login`,{method:'POST',body:JSON.stringify({email:f.get('email'),password:f.get('password')})});localStorage.setItem('opscore_token',data.token);setToken(data.token);setUser(data.user);setPage('Dashboard');}catch(error){setLoginError(error.message);}}

  useEffect(()=>{if(!token){setAuthChecking(false);return;}(async()=>{try{const data=await request(`${ROOT}/auth/me`);setUser(data.user);}catch{}finally{setAuthChecking(false);}})();},[token]);

  async function refresh(){
    if(!token||!user)return;
    try{
      setLoading(true);
      const [d,i,r,a,s]=await Promise.all([json('/dashboard'),json('/incidents'),json('/requests'),json('/assets'),json('/sites')]);
      setDashboard(d);setIncidents(i);setRequests(r);setAssets(a);setSites(s);setApiState('Healthy');
      if(isAdmin){try{setUsers(await json('/users'));}catch{}}
      if(selectedSite){try{setLocations(await json(`/sites/${selectedSite.id}/locations`));}catch{}}
    }catch(error){setApiState('Unavailable');notify(error.message);}finally{setLoading(false);}
  }
  useEffect(()=>{if(user)refresh();},[user]);

  const filteredIncidents=useMemo(()=>incidents.filter(i=>`${i.id} ${i.title} ${i.assignmentGroup} ${i.asset}`.toLowerCase().includes(search.toLowerCase())),[incidents,search]);

  async function openSite(site){setSelectedSite(site);setPage('Sites');try{setLocations(await json(`/sites/${site.id}/locations`));}catch(error){notify(error.message);}}
  async function createIncident(e){e.preventDefault();const f=new FormData(e.currentTarget);try{await json('/incidents',{method:'POST',body:JSON.stringify({title:f.get('title'),description:f.get('description'),priority:f.get('priority'),assignmentGroup:f.get('group'),caller:f.get('caller')||user.name,asset:f.get('asset')||'Unassigned'})});setIncidentModal(false);setPage('Incidents');await refresh();notify('Incident created');}catch(error){notify(error.message);}}
  async function createAsset(e){e.preventDefault();const f=new FormData(e.currentTarget);try{await json('/assets',{method:'POST',body:JSON.stringify({name:f.get('name'),type:f.get('type'),siteId:f.get('siteId')||null,locationId:f.get('locationId')||null,owner:f.get('owner'),serialNumber:f.get('serialNumber'),model:f.get('model')})});setAssetModal(false);setPage('Assets / CMDB');await refresh();notify('Asset created');}catch(error){notify(error.message);}}
  async function createUser(e){e.preventDefault();const f=new FormData(e.currentTarget);try{await json('/users',{method:'POST',body:JSON.stringify({name:f.get('name'),email:f.get('email'),role:f.get('role'),password:f.get('password')})});setUserModal(false);await refresh();notify('User created');}catch(error){notify(error.message);}}
  async function createSite(e){e.preventDefault();const f=new FormData(e.currentTarget);try{const site=await json('/sites',{method:'POST',body:JSON.stringify({code:f.get('code'),name:f.get('name'),siteType:f.get('siteType'),address1:f.get('address1'),city:f.get('city'),postcode:f.get('postcode'),owner:f.get('owner'),status:f.get('status'),notes:f.get('notes')})});setSiteModal(false);await refresh();await openSite(site);notify('Site created');}catch(error){notify(error.message);}}
  async function createLocation(e){e.preventDefault();const f=new FormData(e.currentTarget);try{await json(`/sites/${selectedSite.id}/locations`,{method:'POST',body:JSON.stringify({code:f.get('code'),name:f.get('name'),locationType:f.get('locationType'),parentLocationId:f.get('parentLocationId')||null,floor:f.get('floor'),status:f.get('status'),notes:f.get('notes')})});setLocationModal(false);setLocations(await json(`/sites/${selectedSite.id}/locations`));await refresh();notify('Location created');}catch(error){notify(error.message);}}
  async function closeIncident(id){try{await json(`/incidents/${id}`,{method:'PATCH',body:JSON.stringify({status:'Closed'})});await refresh();notify(`${id} closed`);}catch(error){notify(error.message);}}

  if(authChecking)return <div className="authScreen"><div className="authCard"><div className="logoMark big">O</div><h1>OpsCore</h1><p>Checking secure session…</p></div></div>;
  if(!token||!user)return <div className="authScreen"><form className="authCard" onSubmit={login}><div className="logoMark big">O</div><div><h1>OpsCore</h1><p>Enterprise Operations Platform</p></div><label>Email<input name="email" type="email" required autoFocus placeholder="admin@opscore.local"/></label><label>Password<input name="password" type="password" required/></label>{loginError&&<div className="authError">{loginError}</div>}<button className="primary authButton">Sign in</button><small>OpsCore v5 · Protected workspace</small></form></div>;

  function Dashboard(){const cards=[['Open Incidents',dashboard.incidents,'Incidents'],['Managed Assets',dashboard.assets,'Assets / CMDB'],['Sites',dashboard.sites,'Sites'],['Locations',dashboard.locations,'Sites']];return <><section className="cards">{cards.map(([t,v,target])=><button className="card" key={t} onClick={()=>setPage(target)}><span>{t}</span><strong>{loading?'…':v}</strong><small>Open workspace →</small></button>)}</section><section className="modules"><button className="module service" onClick={()=>setPage('Incidents')}><div className="moduleIcon">S</div><div><h3>OpsCore Service</h3><p>Secure incidents, requests and operational workflows.</p><Badge tone="green">Live</Badge></div></button><button className="module infra" onClick={()=>setPage('Sites')}><div className="moduleIcon">I</div><div><h3>OpsCore Infrastructure</h3><p>Shared sites and locations now form the foundation for Server Room Manager.</p><Badge tone="green">Foundation live</Badge></div></button><button className="module compliance" onClick={()=>setPage('Sites')}><div className="moduleIcon">C</div><div><h3>OpsCore Compliance</h3><p>DCAM can now reference the same site and location identities.</p><Badge tone="purple">Foundation live</Badge></div></button></section><section className="grid2"><div className="panel"><div className="panelHead"><div><h2>Priority incidents</h2><p>Live from PostgreSQL</p></div><button className="linkBtn" onClick={()=>setPage('Incidents')}>View all</button></div>{incidents.slice(0,4).map(i=><div className="row" key={i.id}><span className="mono">{i.id}</span><strong>{i.title}</strong><Badge tone={i.priority==='P1'?'red':i.priority==='P2'?'amber':'blue'}>{i.priority}</Badge><span>{i.assignmentGroup}</span></div>)}</div><div className="panel"><div className="panelHead"><div><h2>Platform foundation</h2><p>Shared OpsCore services</p></div></div><div className="health"><span><i className="ok"/>Identity & roles</span><b>{user.role}</b></div><div className="health"><span><i className={apiState==='Healthy'?'ok':'warn'}/>API</span><b>{apiState}</b></div><div className="health"><span><i className="ok"/>Sites</span><b>{dashboard.sites}</b></div><div className="health"><span><i className="ok"/>Locations</span><b>{dashboard.locations}</b></div></div></section></>}

  function Sites(){
    if(selectedSite)return <section className="siteWorkspace"><div className="panel siteHero"><div><button className="linkBtn" onClick={()=>{setSelectedSite(null);setLocations([])}}>← All sites</button><div className="siteTitle"><div className="siteIcon">{selectedSite.code?.slice(0,2)}</div><div><div className="eyebrow">{selectedSite.code}</div><h2>{selectedSite.name}</h2><p>{[selectedSite.address1,selectedSite.city,selectedSite.postcode].filter(Boolean).join(', ')||'Address not yet set'}</p></div></div></div><div className="siteMeta"><Badge tone="green">{selectedSite.status}</Badge><strong>{selectedSite.siteType}</strong></div></div><div className="siteStats"><div className="panel stat"><span>Locations</span><strong>{locations.length}</strong></div><div className="panel stat"><span>Assets</span><strong>{assets.filter(a=>Number(a.siteId)===Number(selectedSite.id)).length}</strong></div><div className="panel stat"><span>Owner</span><strong className="smallStat">{selectedSite.owner||'Unassigned'}</strong></div></div><div className="panel"><div className="panelHead"><div><h2>Locations</h2><p>Buildings, floors, rooms and operational spaces within this site.</p></div>{canWriteSites&&<button className="primary" onClick={()=>setLocationModal(true)}>+ Add location</button>}</div><div className="table locationTable"><div className="thead"><span>Code</span><span>Location</span><span>Type</span><span>Parent</span><span>Floor</span><span>Assets</span></div>{locations.map(l=><div className="trow" key={l.id}><span className="mono">{l.code}</span><strong>{l.name}</strong><span>{l.locationType}</span><span>{l.parentName||'—'}</span><span>{l.floor||'—'}</span><span>{l.assetCount}</span></div>)}</div></div></section>;
    return <section className="panel"><div className="panelHead"><div><h2>Sites</h2><p>Shared physical locations used by Service, Infrastructure and Compliance.</p></div>{canWriteSites&&<button className="primary" onClick={()=>setSiteModal(true)}>+ Add site</button>}</div><div className="siteGrid">{sites.map(s=><button className="siteCard" key={s.id} onClick={()=>openSite(s)}><div className="siteCardTop"><div className="siteIcon">{s.code.slice(0,2)}</div><Badge tone={s.status==='Operational'?'green':'amber'}>{s.status}</Badge></div><h3>{s.name}</h3><span className="mono">{s.code}</span><p>{[s.city,s.postcode].filter(Boolean).join(' · ')||s.siteType}</p><div className="siteCounts"><span><b>{s.locationCount}</b> locations</span><span><b>{s.assetCount}</b> assets</span></div></button>)}</div></section>;
  }

  function Incidents(){return <section className="panel"><div className="toolbar"><div><h2>Incidents</h2><p>Role-protected Service Management records.</p></div><div className="toolbarActions"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search incidents"/>{canWriteIncidents&&<button className="primary" onClick={()=>setIncidentModal(true)}>+ New incident</button>}</div></div><div className="table"><div className="thead"><span>Number</span><span>Summary</span><span>Priority</span><span>Status</span><span>Assignment group</span><span>Action</span></div>{filteredIncidents.map(i=><div className="trow" key={i.id}><span className="mono">{i.id}</span><strong>{i.title}</strong><span><Badge tone={i.priority==='P1'?'red':i.priority==='P2'?'amber':'blue'}>{i.priority}</Badge></span><span>{i.status}</span><span>{i.assignmentGroup}</span><span>{canWriteIncidents&&i.status!=='Closed'?<button className="miniBtn" onClick={()=>closeIncident(i.id)}>Close</button>:<Badge tone={i.status==='Closed'?'green':'blue'}>{i.status}</Badge>}</span></div>)}</div></section>}
  function Requests(){return <section className="panel"><div className="panelHead"><div><h2>Service requests</h2><p>Shared request queue.</p></div></div>{requests.map(r=><div className="row request" key={r.id}><span className="mono">{r.id}</span><strong>{r.title}</strong><span>{r.requestedFor}</span><Badge>{r.status}</Badge></div>)}</section>}
  function Assets(){return <section className="panel"><div className="panelHead"><div><h2>Assets / CMDB</h2><p>Configuration items linked to shared OpsCore sites and locations.</p></div>{canWriteAssets&&<button className="primary" onClick={()=>setAssetModal(true)}>+ Add asset</button>}</div><div className="table assets"><div className="thead"><span>ID</span><span>Configuration item</span><span>Type</span><span>Site / location</span><span>Owner</span><span>State</span></div>{assets.map(a=><div className="trow" key={a.id}><span className="mono">{a.id}</span><strong>{a.name}</strong><span>{a.type}</span><span>{a.location?`${a.site} / ${a.location}`:a.site||'—'}</span><span>{a.owner}</span><span><Badge tone="green">{a.state}</Badge></span></div>)}</div></section>}
  function Administration(){if(!isAdmin)return <section className="panel empty"><div className="emptyIcon">🔒</div><h2>Administration</h2><p>Your role does not have platform administration permission.</p></section>;return <section className="panel"><div className="panelHead"><div><h2>Users & access</h2><p>Manage local OpsCore accounts and roles.</p></div><button className="primary" onClick={()=>setUserModal(true)}>+ Add user</button></div><div className="table usersTable"><div className="thead"><span>Name</span><span>Email</span><span>Role</span><span>Status</span><span>Last login</span><span>Access</span></div>{users.map(u=><div className="trow" key={u.id}><strong>{u.name}</strong><span>{u.email}</span><span><Badge>{u.role}</Badge></span><span>{u.active?'Active':'Disabled'}</span><span>{u.lastLoginAt?new Date(u.lastLoginAt).toLocaleString():'Never'}</span><span>{u.active?'Allowed':'Blocked'}</span></div>)}</div></section>}
  function Integration({type}){const infra=type==='Infrastructure';return <section className="panel heroPanel"><Badge tone={infra?'blue':'purple'}>{infra?'OpsCore Infrastructure':'OpsCore Compliance'}</Badge><h2>{page}</h2><p>{infra?'This workspace will use the live site/location foundation created in v5, then absorb rack and server-room data.':'This workspace will use the same live site/location foundation for DCAM audits, inspections and evidence.'}</p><div className="integrationMap"><div>Shared Sites</div><span>→</span><div>{infra?'Server Room Manager':'DCAM'}</div><span>→</span><div>Shared CMDB</div></div></section>}
  function Generic(){return <section className="panel empty"><div className="emptyIcon">◇</div><h2>{page}</h2><p>This workspace is wired into OpsCore navigation and ready for its next functional module.</p><button className="secondary" onClick={()=>setPage('Dashboard')}>Back to dashboard</button></section>}
  function Current(){if(page==='Dashboard')return <Dashboard/>;if(page==='Sites')return <Sites/>;if(page==='Incidents')return <Incidents/>;if(page==='Requests')return <Requests/>;if(page==='Assets / CMDB')return <Assets/>;if(page==='Administration')return <Administration/>;if(['Server Rooms','Racks','Equipment'].includes(page))return <Integration type="Infrastructure"/>;if(['Audits','Inspections','Evidence'].includes(page))return <Integration type="Compliance"/>;return <Generic/>}

  return <div className="app"><aside><div className="logoRow"><div className="logoMark">O</div><div><div className="brand">OpsCore</div><div className="sub">Enterprise Operations</div></div></div><nav><button className={page==='Dashboard'?'active':''} onClick={()=>{setPage('Dashboard');setSelectedSite(null)}}>⌂ <span>Dashboard</span></button>{navGroups.map(([group,items])=><React.Fragment key={group}><h4>{group}</h4>{items.map(item=><button key={item} className={page===item?'active':''} onClick={()=>{setPage(item);if(item!=='Sites')setSelectedSite(null)}}><span>{item}</span></button>)}</React.Fragment>)}</nav><div className="asideFooter"><div className="avatar">{user.name.split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase()}</div><div><strong>{user.name}</strong><span>{user.role} · v5</span></div></div></aside><main><header><div><div className="eyebrow">OpsCore / {page}</div><h1>{page==='Dashboard'?'Operations Dashboard':selectedSite&&page==='Sites'?selectedSite.name:page}</h1><p>{page==='Dashboard'?'Service, infrastructure and compliance in one secure workspace.':page==='Sites'?'Shared enterprise physical location model.':`OpsCore ${page} workspace`}</p></div><div className="headActions"><Badge tone="green">{user.role}</Badge><button className="iconBtn" onClick={refresh}>↻</button><button className="secondary" onClick={()=>logout()}>Sign out</button><span className="pill">v5</span></div></header><Current/></main>

  {incidentModal&&<div className="modalBack" onMouseDown={()=>setIncidentModal(false)}><form className="modal" onSubmit={createIncident} onMouseDown={e=>e.stopPropagation()}><div className="panelHead"><div><h2>New incident</h2><p>Saved to OpsCore PostgreSQL.</p></div><button type="button" className="close" onClick={()=>setIncidentModal(false)}>×</button></div><label>Summary<input name="title" required autoFocus/></label><label>Description<input name="description"/></label><div className="formGrid"><label>Priority<select name="priority"><option>P3</option><option>P4</option><option>P2</option><option>P1</option></select></label><label>Assignment group<select name="group"><option>Service Desk</option><option>Deskside</option><option>Infrastructure</option><option>Networks</option></select></label></div><div className="formGrid"><label>Caller<input name="caller" defaultValue={user.name}/></label><label>Asset / CI<input name="asset"/></label></div><div className="modalActions"><button type="button" className="secondary" onClick={()=>setIncidentModal(false)}>Cancel</button><button className="primary">Create incident</button></div></form></div>}

  {assetModal&&<div className="modalBack" onMouseDown={()=>setAssetModal(false)}><form className="modal" onSubmit={createAsset} onMouseDown={e=>e.stopPropagation()}><div className="panelHead"><div><h2>New asset</h2><p>Create a shared CMDB record.</p></div><button type="button" className="close" onClick={()=>setAssetModal(false)}>×</button></div><div className="formGrid"><label>Name<input name="name" required autoFocus/></label><label>Type<select name="type"><option>Server</option><option>Laptop</option><option>Network Switch</option><option>Printer</option><option>UPS</option><option>Rack</option><option>Other</option></select></label></div><div className="formGrid"><label>Site<select name="siteId"><option value="">Unassigned</option>{sites.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label><label>Location ID<input name="locationId" placeholder="Optional location ID"/></label></div><div className="formGrid"><label>Owner<input name="owner"/></label><label>Serial number<input name="serialNumber"/></label></div><label>Model<input name="model"/></label><div className="modalActions"><button type="button" className="secondary" onClick={()=>setAssetModal(false)}>Cancel</button><button className="primary">Create asset</button></div></form></div>}

  {userModal&&<div className="modalBack" onMouseDown={()=>setUserModal(false)}><form className="modal" onSubmit={createUser} onMouseDown={e=>e.stopPropagation()}><div className="panelHead"><div><h2>New OpsCore user</h2><p>Create a local account and assign its platform role.</p></div><button type="button" className="close" onClick={()=>setUserModal(false)}>×</button></div><div className="formGrid"><label>Name<input name="name" required autoFocus/></label><label>Email<input name="email" type="email" required/></label></div><div className="formGrid"><label>Role<select name="role">{roles.map(r=><option key={r}>{r}</option>)}</select></label><label>Temporary password<input name="password" type="password" minLength="10" required/></label></div><div className="modalActions"><button type="button" className="secondary" onClick={()=>setUserModal(false)}>Cancel</button><button className="primary">Create user</button></div></form></div>}

  {siteModal&&<div className="modalBack" onMouseDown={()=>setSiteModal(false)}><form className="modal" onSubmit={createSite} onMouseDown={e=>e.stopPropagation()}><div className="panelHead"><div><h2>New site</h2><p>Create a shared physical site for all OpsCore modules.</p></div><button type="button" className="close" onClick={()=>setSiteModal(false)}>×</button></div><div className="formGrid"><label>Site code<input name="code" required autoFocus placeholder="WKG-02"/></label><label>Site name<input name="name" required placeholder="Workington Secondary Site"/></label></div><div className="formGrid"><label>Type<select name="siteType"><option>Office</option><option>Office / Data Centre</option><option>Data Centre</option><option>Warehouse</option><option>Retail</option><option>Remote Site</option><option>Other</option></select></label><label>Status<select name="status"><option>Operational</option><option>Planned</option><option>Maintenance</option><option>Retired</option></select></label></div><label>Address<input name="address1"/></label><div className="formGrid"><label>Town / city<input name="city"/></label><label>Postcode<input name="postcode"/></label></div><label>Owner / department<input name="owner"/></label><label>Notes<input name="notes"/></label><div className="modalActions"><button type="button" className="secondary" onClick={()=>setSiteModal(false)}>Cancel</button><button className="primary">Create site</button></div></form></div>}

  {locationModal&&selectedSite&&<div className="modalBack" onMouseDown={()=>setLocationModal(false)}><form className="modal" onSubmit={createLocation} onMouseDown={e=>e.stopPropagation()}><div className="panelHead"><div><h2>New location</h2><p>Add a building, floor, server room or operational space to {selectedSite.name}.</p></div><button type="button" className="close" onClick={()=>setLocationModal(false)}>×</button></div><div className="formGrid"><label>Code<input name="code" required autoFocus placeholder="SR-02"/></label><label>Name<input name="name" required placeholder="Server Room 2"/></label></div><div className="formGrid"><label>Type<select name="locationType"><option>Building</option><option>Floor</option><option>Server Room</option><option>Comms Room</option><option>Office</option><option>Plant Room</option><option>Storage</option><option>Other</option></select></label><label>Floor<input name="floor" placeholder="Ground"/></label></div><div className="formGrid"><label>Parent location<select name="parentLocationId"><option value="">None</option>{locations.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label><label>Status<select name="status"><option>Operational</option><option>Planned</option><option>Maintenance</option><option>Retired</option></select></label></div><label>Notes<input name="notes"/></label><div className="modalActions"><button type="button" className="secondary" onClick={()=>setLocationModal(false)}>Cancel</button><button className="primary">Create location</button></div></form></div>}

  {toast&&<div className="toast">{toast}</div>}
  </div>;
}

createRoot(document.getElementById('root')).render(<App/>);
