import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';
import './infrastructure-v6.css';
import './equipment-v7.css';
import RackEquipmentPanel from './RackEquipmentPanel.jsx';

const ROOT='';
const API='/api';
const navGroups=[['Service',['Incidents','Requests','Problems','Changes','Knowledge']],['Infrastructure',['Sites','Server Rooms','Racks','Equipment']],['Compliance',['Audits','Inspections','Evidence']],['Platform',['Assets / CMDB','Reporting','Administration']]];
const roles=['Administrator','Service Desk','Engineer','Infrastructure','Auditor','Read Only'];
const rackSizes=[12,18,22,24,27,32,36,42,45,47,48];

function Badge({children,tone='blue'}){return <span className={`badge ${tone}`}>{children}</span>}
function toneForStatus(status){return ['Operational','Installed','Active'].includes(status)?'green':['Retired','Failed'].includes(status)?'red':'amber'}
function Detail({label,value}){return <div className="detailItem"><span>{label}</span><b>{value}</b></div>}

function App(){
  const [token,setToken]=useState(()=>localStorage.getItem('opscore_token')||'');
  const [user,setUser]=useState(null);const [authChecking,setAuthChecking]=useState(Boolean(token));const [loginError,setLoginError]=useState('');
  const [page,setPage]=useState('Dashboard');const [incidents,setIncidents]=useState([]);const [requests,setRequests]=useState([]);const [assets,setAssets]=useState([]);const [users,setUsers]=useState([]);
  const [sites,setSites]=useState([]);const [locations,setLocations]=useState([]);const [allLocations,setAllLocations]=useState([]);const [serverRooms,setServerRooms]=useState([]);const [racks,setRacks]=useState([]);
  const [selectedSite,setSelectedSite]=useState(null);const [selectedRoom,setSelectedRoom]=useState(null);const [selectedRack,setSelectedRack]=useState(null);
  const [dashboard,setDashboard]=useState({incidents:0,requests:0,assets:0,users:0,sites:0,locations:0,serverRooms:0,racks:0});const [search,setSearch]=useState('');
  const [incidentModal,setIncidentModal]=useState(false);const [assetModal,setAssetModal]=useState(false);const [userModal,setUserModal]=useState(false);const [siteModal,setSiteModal]=useState(false);const [locationModal,setLocationModal]=useState(false);const [roomModal,setRoomModal]=useState(false);const [rackModal,setRackModal]=useState(false);
  const [toast,setToast]=useState('');const [loading,setLoading]=useState(false);const [apiState,setApiState]=useState('Connecting');

  const notify=text=>{setToast(text);window.setTimeout(()=>setToast(''),2400)};
  const canWriteIncidents=['Administrator','Service Desk','Engineer','Infrastructure'].includes(user?.role);const canWriteAssets=['Administrator','Engineer','Infrastructure'].includes(user?.role);const canWriteInfrastructure=['Administrator','Infrastructure'].includes(user?.role);const isAdmin=user?.role==='Administrator';

  async function request(url,options={}){const headers={'Content-Type':'application/json',...(options.headers||{})};if(token)headers.Authorization=`Bearer ${token}`;const response=await fetch(url,{...options,headers});const body=await response.json().catch(()=>({}));if(response.status===401&&token){logout(false);throw new Error('Session expired')}if(!response.ok)throw new Error(body.error||`HTTP ${response.status}`);return body}
  const json=(path,options={})=>request(`${API}${path}`,options);
  function logout(show=true){localStorage.removeItem('opscore_token');setToken('');setUser(null);setUsers([]);setSites([]);setLocations([]);setAllLocations([]);setServerRooms([]);setRacks([]);setSelectedSite(null);setSelectedRoom(null);setSelectedRack(null);if(show)notify('Signed out')}
  async function login(e){e.preventDefault();setLoginError('');const f=new FormData(e.currentTarget);try{const data=await request(`${ROOT}/auth/login`,{method:'POST',body:JSON.stringify({email:f.get('email'),password:f.get('password')})});localStorage.setItem('opscore_token',data.token);setToken(data.token);setUser(data.user);setPage('Dashboard')}catch(error){setLoginError(error.message)}}
  useEffect(()=>{if(!token){setAuthChecking(false);return}(async()=>{try{const data=await request(`${ROOT}/auth/me`);setUser(data.user)}catch{}finally{setAuthChecking(false)}})()},[token]);

  async function refresh(){if(!token||!user)return;try{setLoading(true);const[d,i,r,a,s,l,rooms,rackData]=await Promise.all([json('/dashboard'),json('/incidents'),json('/requests'),json('/assets'),json('/sites'),json('/locations'),json('/server-rooms'),json('/racks')]);setDashboard(d);setIncidents(i);setRequests(r);setAssets(a);setSites(s);setAllLocations(l);setServerRooms(rooms);setRacks(rackData);setApiState('Healthy');if(isAdmin){try{setUsers(await json('/users'))}catch{}}if(selectedSite){try{setLocations(await json(`/sites/${selectedSite.id}/locations`))}catch{}}}catch(error){setApiState('Unavailable');notify(error.message)}finally{setLoading(false)}}
  useEffect(()=>{if(user)refresh()},[user]);

  const filteredIncidents=useMemo(()=>incidents.filter(i=>`${i.id} ${i.title} ${i.assignmentGroup} ${i.asset}`.toLowerCase().includes(search.toLowerCase())),[incidents,search]);
  async function openSite(site){setSelectedSite(site);setSelectedRoom(null);setSelectedRack(null);setPage('Sites');try{setLocations(await json(`/sites/${site.id}/locations`))}catch(error){notify(error.message)}}
  function openRoom(room){setSelectedRoom(room);setSelectedRack(null);setPage('Server Rooms')}
  function openRack(rack){setSelectedRack(rack);setSelectedRoom(serverRooms.find(room=>Number(room.id)===Number(rack.serverRoomId))||null);setPage('Racks')}
  function navTo(item){setPage(item);if(item!=='Sites')setSelectedSite(null);if(item!=='Server Rooms')setSelectedRoom(null);if(item!=='Racks')setSelectedRack(null)}

  async function createIncident(e){e.preventDefault();const f=new FormData(e.currentTarget);try{await json('/incidents',{method:'POST',body:JSON.stringify({title:f.get('title'),description:f.get('description'),priority:f.get('priority'),assignmentGroup:f.get('group'),caller:f.get('caller')||user.name,asset:f.get('asset')||'Unassigned'})});setIncidentModal(false);setPage('Incidents');await refresh();notify('Incident created')}catch(error){notify(error.message)}}
  async function closeIncident(id){try{await json(`/incidents/${id}`,{method:'PATCH',body:JSON.stringify({status:'Closed'})});await refresh();notify(`${id} closed`)}catch(error){notify(error.message)}}
  async function createAsset(e){e.preventDefault();const f=new FormData(e.currentTarget);try{await json('/assets',{method:'POST',body:JSON.stringify({name:f.get('name'),type:f.get('type'),siteId:f.get('siteId')||null,locationId:f.get('locationId')||null,owner:f.get('owner'),serialNumber:f.get('serialNumber'),model:f.get('model')})});setAssetModal(false);await refresh();setPage('Assets / CMDB');notify('Asset created')}catch(error){notify(error.message)}}
  async function createUser(e){e.preventDefault();const f=new FormData(e.currentTarget);try{await json('/users',{method:'POST',body:JSON.stringify({name:f.get('name'),email:f.get('email'),role:f.get('role'),password:f.get('password')})});setUserModal(false);await refresh();notify('User created')}catch(error){notify(error.message)}}
  async function createSite(e){e.preventDefault();const f=new FormData(e.currentTarget);try{const site=await json('/sites',{method:'POST',body:JSON.stringify({code:f.get('code'),name:f.get('name'),siteType:f.get('siteType'),address1:f.get('address1'),city:f.get('city'),postcode:f.get('postcode'),owner:f.get('owner'),status:f.get('status'),notes:f.get('notes')})});setSiteModal(false);await refresh();await openSite(site);notify('Site created')}catch(error){notify(error.message)}}
  async function createLocation(e){e.preventDefault();const f=new FormData(e.currentTarget);try{await json(`/sites/${selectedSite.id}/locations`,{method:'POST',body:JSON.stringify({code:f.get('code'),name:f.get('name'),locationType:f.get('locationType'),parentLocationId:f.get('parentLocationId')||null,floor:f.get('floor'),status:f.get('status'),notes:f.get('notes')})});setLocationModal(false);setLocations(await json(`/sites/${selectedSite.id}/locations`));await refresh();notify('Location created')}catch(error){notify(error.message)}}
  async function createServerRoom(e){e.preventDefault();const f=new FormData(e.currentTarget);try{const room=await json('/server-rooms',{method:'POST',body:JSON.stringify({siteId:f.get('siteId'),locationId:f.get('locationId')||null,code:f.get('code'),name:f.get('name'),floor:f.get('floor'),owner:f.get('owner'),status:f.get('status'),maxRacks:f.get('maxRacks'),powerCapacityKw:f.get('powerCapacityKw'),coolingCapacityKw:f.get('coolingCapacityKw'),notes:f.get('notes')})});setRoomModal(false);await refresh();openRoom(room);notify('Server room created')}catch(error){notify(error.message)}}
  async function createRack(e){e.preventDefault();const f=new FormData(e.currentTarget);try{const rack=await json('/racks',{method:'POST',body:JSON.stringify({serverRoomId:f.get('serverRoomId'),rackCode:f.get('rackCode'),name:f.get('name'),manufacturer:f.get('manufacturer'),model:f.get('model'),rackUnits:f.get('rackUnits'),widthMm:f.get('widthMm'),depthMm:f.get('depthMm'),maxWeightKg:f.get('maxWeightKg'),powerCapacityKw:f.get('powerCapacityKw'),coolingCapacityKw:f.get('coolingCapacityKw'),assetTag:f.get('assetTag'),serialNumber:f.get('serialNumber'),owner:f.get('owner'),department:f.get('department'),status:f.get('status'),lifecycleState:f.get('lifecycleState'),positionLabel:f.get('positionLabel'),notes:f.get('notes')})});setRackModal(false);await refresh();openRack(rack);notify('Rack created')}catch(error){notify(error.message)}}

  if(authChecking)return <div className="authScreen"><div className="authCard"><div className="logoMark big">CO</div><h1>Core Ops Workflow</h1><p>Checking secure Core Ops session…</p></div></div>;
  if(!token||!user)return <div className="authScreen"><form className="authCard" onSubmit={login}><div className="logoMark big">CO</div><div><h1>Core Ops Workflow</h1><p>Service, infrastructure and compliance operations.</p></div><label>Email<input name="email" type="email" required autoFocus placeholder="admin@opscore.local"/></label><label>Password<input name="password" type="password" required/></label>{loginError&&<div className="authError">{loginError}</div>}<button className="primary authButton">Sign in</button><small>Core Ops Workflow v38 · Protected workspace</small></form></div>;

  function Dashboard(){const cards=[['Open Incidents',dashboard.incidents,'Incidents'],['Managed Assets',dashboard.assets,'Assets / CMDB'],['Server Rooms',dashboard.serverRooms,'Server Rooms'],['Racks',dashboard.racks,'Racks']];return <><section className="cards">{cards.map(([t,v,target])=><button className="card" key={t} onClick={()=>navTo(target)}><span>{t}</span><strong>{loading?'…':v}</strong><small>Open workspace →</small></button>)}</section><section className="modules"><button className="module service" onClick={()=>navTo('Incidents')}><div className="moduleIcon">S</div><div><h3>Core Ops Service</h3><p>Secure incidents, requests and operational workflows.</p><Badge tone="green">Live</Badge></div></button><button className="module infra" onClick={()=>navTo('Equipment')}><div className="moduleIcon">I</div><div><h3>Core Ops Infrastructure</h3><p>Sites, rooms, racks and U-level equipment placement in one model.</p><Badge tone="green">Equipment live</Badge></div></button><button className="module compliance" onClick={()=>navTo('Sites')}><div className="moduleIcon">C</div><div><h3>Core Ops Compliance</h3><p>DCAM can reference the same physical hierarchy and CMDB identities.</p><Badge tone="purple">Foundation live</Badge></div></button></section><section className="grid2"><div className="panel"><div className="panelHead"><div><h2>Priority incidents</h2><p>Live from PostgreSQL</p></div><button className="linkBtn" onClick={()=>navTo('Incidents')}>View all</button></div>{incidents.slice(0,4).map(i=><div className="row" key={i.id}><span className="mono">{i.id}</span><strong>{i.title}</strong><Badge tone={i.priority==='P1'?'red':i.priority==='P2'?'amber':'blue'}>{i.priority}</Badge><span>{i.assignmentGroup}</span></div>)}</div><div className="panel"><div className="panelHead"><div><h2>Infrastructure</h2><p>Physical operations status</p></div></div><div className="health"><span><i className="ok"/>Sites</span><b>{dashboard.sites}</b></div><div className="health"><span><i className="ok"/>Server rooms</span><b>{dashboard.serverRooms}</b></div><div className="health"><span><i className="ok"/>Racks</span><b>{dashboard.racks}</b></div><div className="health"><span><i className={apiState==='Healthy'?'ok':'warn'}/>API</span><b>{apiState}</b></div></div></section></>}

  function Sites(){if(selectedSite)return <section className="roomWorkspace"><div className="panel roomHero"><div><button className="linkBtn" onClick={()=>{setSelectedSite(null);setLocations([])}}>← All sites</button><div className="roomHeroTitle"><div className="siteIcon">{selectedSite.code?.slice(0,2)}</div><div><div className="eyebrow">{selectedSite.code}</div><h2>{selectedSite.name}</h2><p>{[selectedSite.address1,selectedSite.city,selectedSite.postcode].filter(Boolean).join(', ')||'Address not yet set'}</p></div></div></div><div className="roomHeroMeta"><Badge tone={toneForStatus(selectedSite.status)}>{selectedSite.status}</Badge><strong>{selectedSite.siteType}</strong></div></div><div className="infraStats"><div className="panel infraStat"><span>Locations</span><strong>{locations.length}</strong></div><div className="panel infraStat"><span>Assets</span><strong>{assets.filter(a=>Number(a.siteId)===Number(selectedSite.id)).length}</strong></div><div className="panel infraStat"><span>Server rooms</span><strong>{serverRooms.filter(r=>Number(r.siteId)===Number(selectedSite.id)).length}</strong></div></div><div className="panel"><div className="panelHead"><div><h2>Locations</h2><p>Buildings, floors, rooms and operational spaces.</p></div>{canWriteInfrastructure&&<button className="primary" onClick={()=>setLocationModal(true)}>+ Add location</button>}</div><div className="table locationTable"><div className="thead"><span>Code</span><span>Location</span><span>Type</span><span>Parent</span><span>Floor</span><span>Assets</span></div>{locations.map(l=><div className="trow" key={l.id}><span className="mono">{l.code}</span><strong>{l.name}</strong><span>{l.locationType}</span><span>{l.parentName||'—'}</span><span>{l.floor||'—'}</span><span>{l.assetCount}</span></div>)}</div></div></section>;return <section className="panel"><div className="infraToolbar"><div><h2>Sites</h2><p>Shared physical locations used across Core Ops.</p></div>{canWriteInfrastructure&&<button className="primary" onClick={()=>setSiteModal(true)}>+ Add site</button>}</div><div className="roomGrid">{sites.map(s=><button className="roomCard" key={s.id} onClick={()=>openSite(s)}><div className="roomCardTop"><div className="siteIcon">{s.code.slice(0,2)}</div><Badge tone={toneForStatus(s.status)}>{s.status}</Badge></div><h3>{s.name}</h3><span className="mono">{s.code}</span><p>{[s.city,s.postcode].filter(Boolean).join(' · ')||s.siteType}</p><div className="capacityStrip"><span><b>{s.locationCount}</b>Locations</span><span><b>{s.assetCount}</b>Assets</span><span><b>{serverRooms.filter(r=>Number(r.siteId)===Number(s.id)).length}</b>Rooms</span></div></button>)}</div></section>}

  function ServerRooms(){if(selectedRoom){const rr=racks.filter(r=>Number(r.serverRoomId)===Number(selectedRoom.id));const rackPct=Math.min(100,Math.round((rr.length/Math.max(1,selectedRoom.maxRacks))*100));return <section className="roomWorkspace"><div className="panel roomHero"><div><button className="linkBtn" onClick={()=>setSelectedRoom(null)}>← All server rooms</button><div className="roomHeroTitle"><div className="roomGlyph">SR</div><div><div className="eyebrow">{selectedRoom.code}</div><h2>{selectedRoom.name}</h2><p>{selectedRoom.siteName} · {selectedRoom.locationName||selectedRoom.floor||'Location not assigned'}</p></div></div></div><div className="roomHeroMeta"><Badge tone={toneForStatus(selectedRoom.status)}>{selectedRoom.status}</Badge><strong>{selectedRoom.owner||'Unassigned'}</strong></div></div><div className="infraStats"><div className="panel infraStat"><span>Racks</span><strong>{rr.length}/{selectedRoom.maxRacks}</strong></div><div className="panel infraStat"><span>Rack capacity</span><strong>{rackPct}%</strong></div><div className="panel infraStat"><span>Power</span><strong>{selectedRoom.powerCapacityKw} kW</strong></div><div className="panel infraStat"><span>Cooling</span><strong>{selectedRoom.coolingCapacityKw} kW</strong></div><div className="panel infraStat"><span>Floor</span><strong>{selectedRoom.floor||'—'}</strong></div></div><div className="panel"><div className="infraToolbar"><div><h2>Racks in {selectedRoom.name}</h2><p>Cabinet capacity, lifecycle and equipment readiness.</p></div>{canWriteInfrastructure&&<button className="primary" onClick={()=>setRackModal(true)}>+ Add rack</button>}</div>{rr.length?<div className="rackGrid">{rr.map(r=><RackCard key={r.id} rack={r} onClick={()=>openRack(r)}/>)}</div>:<div className="infraEmpty">No racks yet.</div>}</div></section>}return <section className="panel"><div className="infraToolbar"><div><h2>Server Rooms</h2><p>Operational rooms tied to shared sites and locations.</p></div>{canWriteInfrastructure&&<button className="primary" onClick={()=>setRoomModal(true)}>+ Add server room</button>}</div>{serverRooms.length?<div className="roomGrid">{serverRooms.map(room=><button className="roomCard" key={room.id} onClick={()=>openRoom(room)}><div className="roomCardTop"><div className="roomGlyph">SR</div><Badge tone={toneForStatus(room.status)}>{room.status}</Badge></div><h3>{room.name}</h3><span className="mono">{room.code}</span><p>{room.siteName} · {room.locationName||room.floor||'Location not assigned'}</p><div className="capacityStrip"><span><b>{room.rackCount}/{room.maxRacks}</b>Racks</span><span><b>{room.powerCapacityKw} kW</b>Power</span><span><b>{room.coolingCapacityKw} kW</b>Cooling</span></div></button>)}</div>:<div className="infraEmpty">No server rooms configured yet.</div>}</section>}
  function RackCard({rack,onClick}){return <button className="rackCard" onClick={onClick}><div className="rackCardTop"><div className="rackIcon"/><Badge tone={toneForStatus(rack.lifecycleState)}>{rack.lifecycleState}</Badge></div><h3>{rack.name}</h3><div className="mono">{rack.rackCode}</div><div className="rackModel">{[rack.manufacturer,rack.model].filter(Boolean).join(' ')||'Manufacturer/model not set'}</div><div className="rackNumbers"><span><b>{rack.rackUnits}U</b>Height</span><span><b>{rack.widthMm}mm</b>Width</span><span><b>{rack.depthMm}mm</b>Depth</span></div></button>}

  function Racks(){if(selectedRack)return <section className="roomWorkspace"><div className="panel roomHero"><div><button className="linkBtn" onClick={()=>setSelectedRack(null)}>← All racks</button><div className="roomHeroTitle"><div className="rackIcon"/><div><div className="eyebrow">{selectedRack.rackCode}</div><h2>{selectedRack.name}</h2><p>{selectedRack.siteName} · {selectedRack.serverRoomName} · {selectedRack.positionLabel||'Position not set'}</p></div></div></div><div className="roomHeroMeta"><Badge tone={toneForStatus(selectedRack.status)}>{selectedRack.status}</Badge><Badge tone={toneForStatus(selectedRack.lifecycleState)}>{selectedRack.lifecycleState}</Badge></div></div><div className="panel"><div className="panelHead"><div><h2>Rack specification</h2><p>Physical limits are enforced when equipment is placed.</p></div></div><div className="detailGrid"><Detail label="Rack units" value={`${selectedRack.rackUnits}U`}/><Detail label="Dimensions" value={`${selectedRack.widthMm} × ${selectedRack.depthMm} mm`}/><Detail label="Max weight" value={`${selectedRack.maxWeightKg||0} kg`}/><Detail label="Power capacity" value={`${selectedRack.powerCapacityKw||0} kW`}/><Detail label="Cooling capacity" value={`${selectedRack.coolingCapacityKw||0} kW`}/><Detail label="Asset tag" value={selectedRack.assetTag||'—'}/><Detail label="Serial number" value={selectedRack.serialNumber||'—'}/><Detail label="Owner" value={selectedRack.owner||'—'}/><Detail label="Department" value={selectedRack.department||'—'}/><Detail label="Model" value={[selectedRack.manufacturer,selectedRack.model].filter(Boolean).join(' ')||'—'}/></div></div><RackEquipmentPanel rack={selectedRack} request={request} canWrite={canWriteInfrastructure}/></section>;return <section className="panel"><div className="infraToolbar"><div><h2>Racks</h2><p>All cabinets across Core Ops server rooms.</p></div>{canWriteInfrastructure&&serverRooms.length>0&&<button className="primary" onClick={()=>setRackModal(true)}>+ Add rack</button>}</div>{racks.length?<div className="rackGrid">{racks.map(r=><RackCard key={r.id} rack={r} onClick={()=>openRack(r)}/>)}</div>:<div className="infraEmpty">No racks configured yet.</div>}</section>}
  function Equipment(){return <section className="panel"><div className="infraToolbar"><div><h2>Rack Equipment</h2><p>Select a rack to place servers, switches, storage and other rack-mounted devices.</p></div></div>{racks.length?<div className="rackGrid">{racks.map(r=><RackCard key={r.id} rack={r} onClick={()=>openRack(r)}/>)}</div>:<div className="infraEmpty">Create a rack before placing equipment.</div>}</section>}

  function Incidents(){return <section className="panel"><div className="toolbar"><div><h2>Incidents</h2><p>Role-protected Service Management records.</p></div><div className="toolbarActions"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search incidents"/>{canWriteIncidents&&<button className="primary" onClick={()=>setIncidentModal(true)}>+ New incident</button>}</div></div><div className="table"><div className="thead"><span>Number</span><span>Summary</span><span>Priority</span><span>Status</span><span>Assignment group</span><span>Action</span></div>{filteredIncidents.map(i=><div className="trow" key={i.id}><span className="mono">{i.id}</span><strong>{i.title}</strong><span><Badge tone={i.priority==='P1'?'red':i.priority==='P2'?'amber':'blue'}>{i.priority}</Badge></span><span>{i.status}</span><span>{i.assignmentGroup}</span><span>{canWriteIncidents&&i.status!=='Closed'?<button className="miniBtn" onClick={()=>closeIncident(i.id)}>Close</button>:<Badge tone={i.status==='Closed'?'green':'blue'}>{i.status}</Badge>}</span></div>)}</div></section>}
  function Requests(){return <section className="panel"><div className="panelHead"><div><h2>Service requests</h2><p>Shared request queue.</p></div></div>{requests.map(r=><div className="row request" key={r.id}><span className="mono">{r.id}</span><strong>{r.title}</strong><span>{r.requestedFor}</span><Badge>{r.status}</Badge></div>)}</section>}
  function Assets(){return <section className="panel"><div className="panelHead"><div><h2>Assets / CMDB</h2><p>Configuration items linked to shared sites and locations.</p></div>{canWriteAssets&&<button className="primary" onClick={()=>setAssetModal(true)}>+ Add asset</button>}</div><div className="table assets"><div className="thead"><span>ID</span><span>Configuration item</span><span>Type</span><span>Site / location</span><span>Owner</span><span>State</span></div>{assets.map(a=><div className="trow" key={a.id}><span className="mono">{a.id}</span><strong>{a.name}</strong><span>{a.type}</span><span>{a.location?`${a.site} / ${a.location}`:a.site||'—'}</span><span>{a.owner}</span><span><Badge tone="green">{a.state}</Badge></span></div>)}</div></section>}
  function Administration(){if(!isAdmin)return <section className="panel empty"><div className="emptyIcon">🔒</div><h2>Administration</h2><p>Your role does not have platform administration permission.</p></section>;return <section className="panel"><div className="panelHead"><div><h2>Users & access</h2><p>Manage local Core Ops accounts and roles.</p></div><button className="primary" onClick={()=>setUserModal(true)}>+ Add user</button></div><div className="table usersTable"><div className="thead"><span>Name</span><span>Email</span><span>Role</span><span>Status</span><span>Last login</span><span>Access</span></div>{users.map(u=><div className="trow" key={u.id}><strong>{u.name}</strong><span>{u.email}</span><span><Badge>{u.role}</Badge></span><span>{u.active?'Active':'Disabled'}</span><span>{u.lastLoginAt?new Date(u.lastLoginAt).toLocaleString():'Never'}</span><span>{u.active?'Allowed':'Blocked'}</span></div>)}</div></section>}
  function Generic(){return <section className="panel empty"><div className="emptyIcon">◇</div><h2>{page}</h2><p>This workspace is ready for its next functional module.</p><button className="secondary" onClick={()=>navTo('Dashboard')}>Back to dashboard</button></section>}
  function Current(){if(page==='Dashboard')return <Dashboard/>;if(page==='Sites')return <Sites/>;if(page==='Server Rooms')return <ServerRooms/>;if(page==='Racks')return <Racks/>;if(page==='Equipment')return <Equipment/>;if(page==='Incidents')return <Incidents/>;if(page==='Requests')return <Requests/>;if(page==='Assets / CMDB')return <Assets/>;if(page==='Administration')return <Administration/>;return <Generic/>}

  return <div className="app"><aside><div className="logoRow"><div className="logoMark">CO</div><div><div className="brand">Core Ops Workflow</div><div className="sub">Operations platform</div></div></div><nav><button className={page==='Dashboard'?'active':''} onClick={()=>navTo('Dashboard')}>⌂ <span>Dashboard</span></button>{navGroups.map(([group,items])=><React.Fragment key={group}><h4>{group}</h4>{items.map(item=><button key={item} className={page===item?'active':''} onClick={()=>navTo(item)}><span>{item}</span></button>)}</React.Fragment>)}</nav><div className="asideFooter"><div className="avatar">{user.name.split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase()}</div><div><strong>{user.name}</strong><span>{user.role} · v38</span></div></div></aside><main><header><div><div className="eyebrow">Core Ops Workflow / {page}</div><h1>{page==='Dashboard'?'Operations Dashboard':page}</h1><p>{page==='Dashboard'?'Service, infrastructure and compliance in one secure workspace.':page==='Equipment'?'U-level rack equipment placement and capacity.':page==='Racks'?'Rack inventory, capacity and visual equipment elevation.':`Core Ops ${page} workspace`}</p></div><div className="headActions"><Badge tone="green">{user.role}</Badge><button className="iconBtn" onClick={refresh}>↻</button><button className="secondary" onClick={()=>logout()}>Sign out</button><span className="pill">v38</span></div></header><Current/></main>

  {incidentModal&&<div className="modalBack" onMouseDown={()=>setIncidentModal(false)}><form className="modal" onSubmit={createIncident} onMouseDown={e=>e.stopPropagation()}><div className="panelHead"><div><h2>New incident</h2><p>Saved to Core Ops PostgreSQL.</p></div><button type="button" className="close" onClick={()=>setIncidentModal(false)}>×</button></div><label>Summary<input name="title" required autoFocus/></label><label>Description<input name="description"/></label><div className="formGrid"><label>Priority<select name="priority"><option>P3</option><option>P4</option><option>P2</option><option>P1</option></select></label><label>Assignment group<select name="group"><option>Service Desk</option><option>Deskside</option><option>Infrastructure</option><option>Networks</option></select></label></div><div className="formGrid"><label>Caller<input name="caller" defaultValue={user.name}/></label><label>Asset / CI<input name="asset"/></label></div><div className="modalActions"><button type="button" className="secondary" onClick={()=>setIncidentModal(false)}>Cancel</button><button className="primary">Create incident</button></div></form></div>}
  {assetModal&&<div className="modalBack" onMouseDown={()=>setAssetModal(false)}><form className="modal" onSubmit={createAsset} onMouseDown={e=>e.stopPropagation()}><div className="panelHead"><div><h2>New asset</h2><p>Create a shared CMDB record.</p></div><button type="button" className="close" onClick={()=>setAssetModal(false)}>×</button></div><div className="formGrid"><label>Name<input name="name" required autoFocus/></label><label>Type<select name="type"><option>Server</option><option>Laptop</option><option>Network Switch</option><option>Printer</option><option>UPS</option><option>Rack Device</option><option>Other</option></select></label></div><div className="formGrid"><label>Site<select name="siteId"><option value="">Unassigned</option>{sites.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label><label>Location<select name="locationId"><option value="">Unassigned</option>{allLocations.map(l=><option value={l.id} key={l.id}>{l.siteName} / {l.name}</option>)}</select></label></div><div className="formGrid"><label>Owner<input name="owner"/></label><label>Serial number<input name="serialNumber"/></label></div><label>Model<input name="model"/></label><div className="modalActions"><button type="button" className="secondary" onClick={()=>setAssetModal(false)}>Cancel</button><button className="primary">Create asset</button></div></form></div>}
  {userModal&&<div className="modalBack" onMouseDown={()=>setUserModal(false)}><form className="modal" onSubmit={createUser} onMouseDown={e=>e.stopPropagation()}><div className="panelHead"><div><h2>New Core Ops user</h2><p>Create a local account and assign its platform role.</p></div><button type="button" className="close" onClick={()=>setUserModal(false)}>×</button></div><div className="formGrid"><label>Name<input name="name" required autoFocus/></label><label>Email<input name="email" type="email" required/></label></div><div className="formGrid"><label>Role<select name="role">{roles.map(r=><option key={r}>{r}</option>)}</select></label><label>Temporary password<input name="password" type="password" minLength="10" required/></label></div><div className="modalActions"><button type="button" className="secondary" onClick={()=>setUserModal(false)}>Cancel</button><button className="primary">Create user</button></div></form></div>}
  {siteModal&&<div className="modalBack" onMouseDown={()=>setSiteModal(false)}><form className="modal" onSubmit={createSite} onMouseDown={e=>e.stopPropagation()}><div className="panelHead"><div><h2>New site</h2><p>Create a shared physical site.</p></div><button type="button" className="close" onClick={()=>setSiteModal(false)}>×</button></div><div className="formGrid"><label>Site code<input name="code" required autoFocus/></label><label>Site name<input name="name" required/></label></div><div className="formGrid"><label>Type<select name="siteType"><option>Office</option><option>Office / Data Centre</option><option>Data Centre</option><option>Warehouse</option><option>Remote Site</option><option>Other</option></select></label><label>Status<select name="status"><option>Operational</option><option>Planned</option><option>Maintenance</option><option>Retired</option></select></label></div><label>Address<input name="address1"/></label><div className="formGrid"><label>Town / city<input name="city"/></label><label>Postcode<input name="postcode"/></label></div><label>Owner / department<input name="owner"/></label><label>Notes<input name="notes"/></label><div className="modalActions"><button type="button" className="secondary" onClick={()=>setSiteModal(false)}>Cancel</button><button className="primary">Create site</button></div></form></div>}
  {locationModal&&selectedSite&&<div className="modalBack" onMouseDown={()=>setLocationModal(false)}><form className="modal" onSubmit={createLocation} onMouseDown={e=>e.stopPropagation()}><div className="panelHead"><div><h2>New location</h2><p>Add an operational space to {selectedSite.name}.</p></div><button type="button" className="close" onClick={()=>setLocationModal(false)}>×</button></div><div className="formGrid"><label>Code<input name="code" required autoFocus/></label><label>Name<input name="name" required/></label></div><div className="formGrid"><label>Type<select name="locationType"><option>Building</option><option>Floor</option><option>Server Room</option><option>Comms Room</option><option>Office</option><option>Plant Room</option><option>Storage</option><option>Other</option></select></label><label>Floor<input name="floor"/></label></div><div className="formGrid"><label>Parent location<select name="parentLocationId"><option value="">None</option>{locations.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></label><label>Status<select name="status"><option>Operational</option><option>Planned</option><option>Maintenance</option><option>Retired</option></select></label></div><label>Notes<input name="notes"/></label><div className="modalActions"><button type="button" className="secondary" onClick={()=>setLocationModal(false)}>Cancel</button><button className="primary">Create location</button></div></form></div>}
  {roomModal&&<div className="modalBack" onMouseDown={()=>setRoomModal(false)}><form className="modal modalWide" onSubmit={createServerRoom} onMouseDown={e=>e.stopPropagation()}><div className="panelHead"><div><h2>New server room</h2><p>Create a managed room linked to the shared site/location model.</p></div><button type="button" className="close" onClick={()=>setRoomModal(false)}>×</button></div><div className="formGrid"><label>Site<select name="siteId" required autoFocus><option value="">Select site</option>{sites.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label><label>Existing location<select name="locationId"><option value="">None</option>{allLocations.filter(l=>['Server Room','Comms Room','Room'].includes(l.locationType)).map(l=><option value={l.id} key={l.id}>{l.siteName} / {l.name}</option>)}</select></label></div><div className="formGrid"><label>Room code<input name="code" required/></label><label>Room name<input name="name" required/></label></div><div className="formGrid"><label>Floor<input name="floor"/></label><label>Owner<input name="owner" defaultValue="Infrastructure"/></label></div><div className="formGrid"><label>Maximum racks<input name="maxRacks" type="number" min="1" defaultValue="20"/></label><label>Status<select name="status"><option>Operational</option><option>Planned</option><option>Maintenance</option><option>Retired</option></select></label></div><div className="formGrid"><label>Power capacity (kW)<input name="powerCapacityKw" type="number" min="0" step="0.1" defaultValue="0"/></label><label>Cooling capacity (kW)<input name="coolingCapacityKw" type="number" min="0" step="0.1" defaultValue="0"/></label></div><label>Notes<input name="notes"/></label><div className="modalActions"><button type="button" className="secondary" onClick={()=>setRoomModal(false)}>Cancel</button><button className="primary">Create server room</button></div></form></div>}
  {rackModal&&serverRooms.length>0&&<div className="modalBack" onMouseDown={()=>setRackModal(false)}><form className="modal modalWide" onSubmit={createRack} onMouseDown={e=>e.stopPropagation()}><div className="panelHead"><div><h2>New rack</h2><p>Add a cabinet with physical, capacity and lifecycle information.</p></div><button type="button" className="close" onClick={()=>setRackModal(false)}>×</button></div><div className="formGrid"><label>Server room<select name="serverRoomId" required defaultValue={selectedRoom?.id||''}><option value="">Select room</option>{serverRooms.map(r=><option value={r.id} key={r.id}>{r.siteName} / {r.name}</option>)}</select></label><label>Rack size<select name="rackUnits" defaultValue="42">{rackSizes.map(u=><option value={u} key={u}>{u}U</option>)}</select></label></div><div className="formGrid"><label>Rack code<input name="rackCode" required/></label><label>Name<input name="name" required/></label></div><div className="formGrid"><label>Manufacturer<input name="manufacturer"/></label><label>Model<input name="model"/></label></div><div className="formGrid"><label>Width (mm)<input name="widthMm" type="number" min="1" defaultValue="600"/></label><label>Depth (mm)<input name="depthMm" type="number" min="1" defaultValue="1000"/></label></div><div className="formGrid"><label>Max weight (kg)<input name="maxWeightKg" type="number" min="0" step="0.1"/></label><label>Position<input name="positionLabel"/></label></div><div className="formGrid"><label>Power capacity (kW)<input name="powerCapacityKw" type="number" min="0" step="0.1"/></label><label>Cooling capacity (kW)<input name="coolingCapacityKw" type="number" min="0" step="0.1"/></label></div><div className="formGrid"><label>Asset tag<input name="assetTag"/></label><label>Serial number<input name="serialNumber"/></label></div><div className="formGrid"><label>Owner<input name="owner" defaultValue="Infrastructure"/></label><label>Department<input name="department" defaultValue="Infrastructure"/></label></div><div className="formGrid"><label>Status<select name="status"><option>Operational</option><option>Planned</option><option>Maintenance</option><option>Retired</option></select></label><label>Lifecycle<select name="lifecycleState"><option>Planned</option><option>Ordered</option><option>Installed</option><option>Maintenance</option><option>Retired</option></select></label></div><label>Notes<input name="notes"/></label><div className="modalActions"><button type="button" className="secondary" onClick={()=>setRackModal(false)}>Cancel</button><button className="primary">Create rack</button></div></form></div>}
  {toast&&<div className="toast">{toast}</div>}</div>
}

createRoot(document.getElementById('root')).render(<App/>);
