const p16token=()=>localStorage.getItem('opscore_token')||'';
const p16ro=()=>((window.CoreOpsI18n?.getLanguage?.()||localStorage.getItem('coreops_language'))==='ro-RO');
const p16t=(en,rr)=>p16ro()?rr:en;
const p16e=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
async function p16api(path,options={}){const r=await fetch(path,{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${p16token()}`,...(options.headers||{})}}),b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.detail||b.error||`HTTP ${r.status}`);return b}
const p16work=()=>document.getElementById('coreopsDcamWorkspace');
function p16activate(){const main=document.querySelector('.app main');main?.classList.remove('enterpriseModuleActive');main?.classList.add('dcamBridgeActive');document.querySelectorAll('.app aside nav button').forEach(b=>b.classList.remove('active'));document.querySelector('[data-dcam-overview]')?.classList.add('active')}
function p16back(){document.querySelector('[data-dcam-overview]')?.click()}
function p16suggest(local,remote){return remote.find(x=>String(x.email||'').toLowerCase()===String(local.email||'').toLowerCase())}
function p16status(value){return `<span class="p16Status ${String(value).toLowerCase().replace(/\s+/g,'-')}">${p16e(value||'Open')}</span>`}
async function p16open(){if(!p16token())return;p16activate();let w=p16work();if(!w)return;w.innerHTML=`<div class="dcamShell"><section class="dcamHero"><h2>${p16t('Loading shared DCAM workflow…','Se încarcă fluxul DCAM partajat…')}</h2></section></div>`;try{const d=await p16api('/api/dcam/collaboration'),mapped=new Map(d.mappings.map(x=>[Number(x.coreops_user_id),x])),linked=new Map(d.handoffs.map(x=>[Number(x.dcam_work_order_id),x]));w.innerHTML=`<div class="dcamShell p16Shell">
<section class="dcamHero"><div><div class="eyebrow">CORE OPS / DCAM · PHASE 16</div><h2>${p16t('Shared users & workflow','Utilizatori și fluxuri partajate')}</h2><p>${p16t('Map operational identities and hand incidents or requests to DCAM without duplicating accounts or passwords.','Mapați identitățile operaționale și transferați incidente sau solicitări către DCAM fără a duplica conturi sau parole.')}</p></div><button id="p16Back" class="secondary">← ${p16t('DCAM overview','Prezentare DCAM')}</button></section>
<section class="identityStats"><div><span>${p16t('Mapped users','Utilizatori mapați')}</span><strong>${d.mappings.length}/${d.coreopsUsers.filter(x=>x.active).length}</strong></div><div><span>${p16t('DCAM users','Utilizatori DCAM')}</span><strong>${d.dcamUsers.length}</strong></div><div><span>${p16t('Linked work orders','Ordine de lucru legate')}</span><strong>${d.handoffs.length}</strong></div><div><span>${p16t('DCAM work orders','Ordine de lucru DCAM')}</span><strong>${d.workOrders.length}</strong></div></section>
<section class="identityPanel"><div class="panelHead"><div><h3>${p16t('Shared user identity','Identitate utilizator partajată')}</h3><p>${p16t('Email matches are suggested. Credentials stay in their owning application.','Potrivirile de e-mail sunt sugerate. Datele de autentificare rămân în aplicația lor.')}</p></div></div><div class="p16Users">${d.coreopsUsers.filter(x=>x.active).map(u=>{const m=mapped.get(Number(u.id)),suggested=p16suggest(u,d.dcamUsers),selected=m?.dcam_user_id||suggested?.id||'';return `<div class="p16User" data-local-user="${u.id}" data-map-id="${m?.id||''}"><div><b>${p16e(u.name)}</b><span>${p16e(u.email)} · ${p16e(u.role)}</span></div><select><option value="">${p16t('Not mapped','Nemapat')}</option>${d.dcamUsers.map(x=>`<option value="${x.id}" ${Number(selected)===Number(x.id)?'selected':''}>${p16e(x.name)} · ${p16e(x.email)} · ${p16e(x.role)}</option>`).join('')}</select><span class="identityState ${m?'mapped':suggested?'suggested':''}">${m?p16t('Mapped','Mapat'):suggested?p16t('Email match','Potrivire e-mail'):p16t('Unmatched','Fără asociere')}</span><button class="primary" data-map>${m?p16t('Update','Actualizează'):p16t('Save','Salvează')}</button>${m?`<button class="linkBtn" data-unmap>${p16t('Remove','Elimină')}</button>`:''}</div>`}).join('')}</div></section>
<section class="identityPanel"><div class="panelHead"><div><h3>${p16t('Create DCAM handoff','Creați transfer DCAM')}</h3><p>${p16t('Creates one idempotent DCAM work order and records the link in both audit trails.','Creează un ordin de lucru DCAM idempotent și înregistrează legătura în ambele jurnale de audit.')}</p></div></div><form id="p16Handoff" class="p16Form"><label>${p16t('Core Ops record type','Tip înregistrare Core Ops')}<select name="sourceType"><option>Incident</option><option>Request</option></select></label><label>${p16t('Record number','Număr înregistrare')}<input name="sourceId" placeholder="INC000001 / REQ000001" required></label><label>${p16t('Assign to DCAM user','Alocați utilizatorului DCAM')}<select name="dcamUserId"><option value="">${p16t('Unassigned','Nealocat')}</option>${d.dcamUsers.map(x=>`<option value="${x.id}">${p16e(x.name)} · ${p16e(x.email)}</option>`).join('')}</select></label><label>${p16t('DCAM building','Clădire DCAM')}<select name="buildingId"><option value="">—</option>${(d.buildings||[]).map(x=>`<option value="${x.id}">${p16e(x.name)}</option>`).join('')}</select></label><label>${p16t('DCAM asset','Activ DCAM')}<select name="assetId"><option value="">—</option>${(d.assets||[]).map(x=>`<option value="${x.id}">${p16e(x.asset_name||x.name)}</option>`).join('')}</select></label><label>${p16t('Due date','Termen')}<input type="date" name="dueDate"></label><button class="primary">${p16t('Create DCAM work order','Creați ordin de lucru DCAM')}</button></form></section>
<section class="identityPanel"><div class="panelHead"><div><h3>${p16t('Shared workflow status','Stare flux partajat')}</h3><p>${p16t('Live DCAM state with the originating Core Ops record retained.','Stare DCAM live cu înregistrarea Core Ops de origine păstrată.')}</p></div><button id="p16Refresh" class="secondary">${p16t('Refresh','Reîmprospătează')}</button></div><div class="p16Orders">${d.workOrders.map(x=>{const h=linked.get(Number(x.id));return `<article class="${h?'linked':''}"><div><b>${p16e(x.work_order_reference)} · ${p16e(x.title)}</b><span>${p16e(x.building_name||'')} ${x.asset_name?'· '+p16e(x.asset_name):''}</span></div><div><span>${p16e(x.assigned_user_name||p16t('Unassigned','Nealocat'))}</span>${p16status(x.status)}</div>${h?`<strong>${p16e(h.source_type)} ${p16e(h.source_id)}</strong>`:''}</article>`}).join('')||`<p>${p16t('No DCAM work orders.','Nu există ordine de lucru DCAM.')}</p>`}</div></section></div>`;
 w.querySelector('#p16Back').onclick=p16back;w.querySelector('#p16Refresh').onclick=p16open;
 w.querySelectorAll('[data-map]').forEach(b=>b.onclick=async()=>{const row=b.closest('.p16User'),dcamUserId=Number(row.querySelector('select').value);if(!dcamUserId)return;await p16api('/api/dcam/user-mappings',{method:'POST',body:JSON.stringify({coreopsUserId:Number(row.dataset.localUser),dcamUserId})});p16open()});
 w.querySelectorAll('[data-unmap]').forEach(b=>b.onclick=async()=>{const row=b.closest('.p16User');await p16api(`/api/dcam/user-mappings/${row.dataset.mapId}`,{method:'DELETE'});p16open()});
 w.querySelector('#p16Handoff').onsubmit=async e=>{e.preventDefault();const body=Object.fromEntries(new FormData(e.currentTarget));try{await p16api('/api/dcam/handoffs',{method:'POST',body:JSON.stringify(body)});p16open()}catch(x){alert(x.message)}};
}catch(e){w.innerHTML=`<div class="dcamShell"><section class="dcamHero"><div><h2>${p16t('Shared workflow unavailable','Fluxul partajat nu este disponibil')}</h2><p>${p16e(e.message)}</p></div><button id="p16Back" class="secondary">← ${p16t('DCAM overview','Prezentare DCAM')}</button></section></div>`;w.querySelector('#p16Back').onclick=p16back}}
window.CoreOpsDcamCollaboration={open:p16open};
document.addEventListener('click',e=>{const b=e.target.closest('#dcamCollaborationOpen');if(b){e.preventDefault();p16open()}},true);
