const s17token=()=>localStorage.getItem('opscore_token')||'';
const s17esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
async function s17api(path,options={}){const r=await fetch(path,{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${s17token()}`,...(options.headers||{})}}),b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.detail||b.error||`HTTP ${r.status}`);return b}
const s17work=()=>document.getElementById('coreopsDcamWorkspace');
function s17activate(){const main=document.querySelector('.app main');main?.classList.remove('enterpriseModuleActive');main?.classList.add('dcamBridgeActive');document.querySelectorAll('.app aside nav button').forEach(b=>b.classList.remove('active'));document.querySelector('[data-dcam-overview]')?.classList.add('active')}
const s17date=v=>v?new Date(v).toLocaleString('en-GB'):'Never';
const s17icon=t=>({User:'U',Site:'S',Asset:'A',Work:'W'}[t]||'D');
function s17error(error){const w=s17work();if(w)w.innerHTML=`<div class="sharedShell"><section class="sharedHero"><div><span>CTEC SHARED DATA</span><h2>Shared data is unavailable</h2><p>${s17esc(error.message||error)}</p></div><button id="s17Retry" class="primary">Retry</button></section></div>`;w?.querySelector('#s17Retry')?.addEventListener('click',s17open)}
async function s17records(type=''){const w=s17work();if(!w)return;const d=await s17api(`/api/shared-data/records${type?`?type=${encodeURIComponent(type)}`:''}`);w.querySelector('#s17Records').innerHTML=d.records.map(x=>`<article class="sharedRecord"><i>${s17icon(x.record_type)}</i><div><b>${s17esc(x.display_name)}</b><span>${s17esc(x.record_type)} · ${s17esc(x.source_app)}${x.natural_key?` · ${s17esc(x.natural_key)}`:''}</span></div><em class="${x.sync_state==='Synced'?'good':'warn'}">${s17esc(x.sync_state)}</em><small>${s17date(x.last_seen_at)}</small></article>`).join('')||'<div class="sharedEmpty">No shared records yet. Select Sync DCAM to import the current records.</div>'}
async function s17open(){if(!s17token())return;s17activate();const w=s17work();if(!w)return;w.innerHTML='<div class="sharedShell"><section class="sharedHero"><h2>Loading CTEC Shared Data…</h2></section></div>';try{const[d,history]=await Promise.all([s17api('/api/shared-data/overview'),s17api('/api/shared-data/sync-history')]),total=d.counts.reduce((n,x)=>n+Number(x.count),0),dcam=d.apps.find(x=>x.app_code==='DCAM'),latest=history.runs?.[0];w.innerHTML=`<div class="sharedShell">
<section class="sharedHero"><div><span>OPSCORE · PHASE 18</span><h2>CTEC Shared Data</h2><p>DCAM synchronises automatically every ${Math.round(history.intervalSeconds/60)} minutes. Records retain their owning application, source identity and audit history.</p></div><button id="s17Sync" class="primary">Sync DCAM now</button></section>
<section class="sharedStats"><div><span>Shared records</span><b>${total}</b></div><div><span>Connected apps</span><b>${d.apps.filter(x=>x.status==='Connected').length}/${d.apps.length}</b></div><div><span>Open conflicts</span><b>${d.conflicts.length}</b></div><div><span>Record types</span><b>${d.counts.length}</b></div></section>
<section class="sharedPanel"><div class="sharedHead"><div><h3>Connected applications</h3><p>Automatic sync is ${dcam?.auto_sync_enabled?'enabled':'disabled'} · Latest run ${latest?s17esc(latest.status)+' at '+s17date(latest.started_at):'pending'}.</p></div></div><div class="sharedApps">${d.apps.map(x=>`<article><div class="sharedAppMark">${s17esc(x.app_code.slice(0,2))}</div><div><b>${s17esc(x.app_name)}</b><span>${Number(x.record_count)} records · Last sync ${s17date(x.last_sync_at)}</span>${x.next_sync_at?`<small>Next automatic sync ${s17date(x.next_sync_at)}</small>`:''}${x.last_error?`<small>${s17esc(x.last_error)}</small>`:''}</div><em class="${x.status==='Connected'?'good':x.status==='Error'?'bad':''}">${s17esc(x.status)}</em></article>`).join('')}</div></section>
<section class="sharedPanel"><div class="sharedHead"><div><h3>Shared records</h3><p>Browse the same business identities without manual pair-by-pair mapping.</p></div><select id="s17Type"><option value="">All record types</option>${d.counts.map(x=>`<option value="${s17esc(x.record_type)}">${s17esc(x.record_type)} (${x.count})</option>`).join('')}</select></div><div id="s17Records"></div></section>
<section class="sharedGrid"><div class="sharedPanel"><div class="sharedHead"><div><h3>Recent shared activity</h3><p>Auditable changes across connected apps.</p></div></div><div class="sharedActivity">${d.activity.map(x=>`<article><i></i><div><b>${s17esc(x.detail)}</b><span>${s17esc(x.source_app)} · ${s17date(x.created_at)}</span></div></article>`).join('')||'<div class="sharedEmpty">No activity recorded yet.</div>'}</div></div><div class="sharedPanel"><div class="sharedHead"><div><h3>Conflict review</h3><p>Only exceptions need manual attention.</p></div></div>${d.conflicts.map(x=>`<article class="sharedConflict"><b>${s17esc(x.record_type)} · ${s17esc(x.natural_key)}</b><span>${s17esc(x.detail)}</span></article>`).join('')||'<div class="sharedEmpty goodText">No open conflicts</div>'}</div></section>
<details class="sharedLegacy"><summary>Legacy mappings and workflow handoffs</summary><p>The Phase 16 tools remain available for rollback and existing handoffs, but are no longer the primary way data is shared.</p><button id="s17Legacy" class="secondary">Open legacy workflow</button></details></div>`;
 w.querySelector('#s17Sync').onclick=async e=>{const b=e.currentTarget;b.disabled=true;b.textContent='Syncing…';try{await s17api('/api/shared-data/sync/dcam',{method:'POST',body:'{}'});await s17open()}catch(error){b.disabled=false;b.textContent='Sync DCAM now';alert(error.message)}};
 w.querySelector('#s17Type').onchange=e=>s17records(e.target.value);w.querySelector('#s17Legacy').onclick=()=>window.CoreOpsDcamCollaboration?.open?.();await s17records();
}catch(error){s17error(error)}}
window.CoreOpsSharedData={open:s17open};
document.addEventListener('click',e=>{const b=e.target.closest('#dcamCollaborationOpen');if(b){e.preventDefault();e.stopImmediatePropagation();s17open()}},true);
