const p3token=()=>localStorage.getItem('opscore_token')||'';
const p3ro=()=>((window.CoreOpsI18n?.getLanguage?.()||localStorage.getItem('coreops_language'))==='ro-RO');
const p3t=(en,rr)=>p3ro()?rr:en;
const p3e=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const p3fmt=v=>v?new Date(v).toLocaleString(p3ro()?'ro-RO':'en-GB'):'—';
async function p3api(path,options={}){const r=await fetch(path,{...options,headers:{'Content-Type':'application/json',...(p3token()?{Authorization:`Bearer ${p3token()}`}:{})}});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||`HTTP ${r.status}`);return b}
function p3workspace(){let w=document.getElementById('coreopsPhase3Workspace');if(!w){w=document.createElement('section');w.id='coreopsPhase3Workspace';document.querySelector('.app main')?.appendChild(w)}return w}
function p3activate(){const main=document.querySelector('.app main');main?.classList.remove('enterpriseModuleActive','dcamBridgeActive','monitoringActive','slaActive','notificationsActive');main?.classList.add('phase3Active');document.querySelectorAll('.app aside nav button').forEach(b=>b.classList.remove('active'))}
function p3deactivate(){document.querySelector('.app main')?.classList.remove('phase3Active')}
function badge(v){return `<span class="p3Badge ${p3e(String(v).toLowerCase().replace(/\s/g,''))}">${p3e(v)}</span>`}
async function openMyWork(){
 if(!p3token())return;p3activate();const w=p3workspace();w.innerHTML=`<div class="p3Shell"><h2>${p3t('Loading My Work…','Se încarcă Activitatea mea…')}</h2></div>`;
 try{const data=await p3api('/api/my-work');w.innerHTML=`<div class="p3Shell"><section class="p3Hero"><div><span>CORE OPS / PHASE 3</span><h2>${p3t('My Work','Activitatea mea')}</h2><p>${p3t('Assigned operational work and approval decisions in one queue.','Activitatea operațională alocată și deciziile de aprobare într-o singură coadă.')}</p></div><div class="p3HeroActions"><a href="/api/exports/incidents.csv">${p3t('Export incidents','Exportă incidente')}</a><a href="/api/exports/requests.csv">${p3t('Export requests','Exportă solicitări')}</a><a href="/api/exports/assets.csv">${p3t('Export assets','Exportă active')}</a></div></section><section class="p3Stats"><article><b>${data.work.length}</b><span>${p3t('Assigned records','Înregistrări alocate')}</span></article><article><b>${data.approvals.length}</b><span>${p3t('Pending approvals','Aprobări în așteptare')}</span></article><article><b>${data.work.filter(x=>x.priority==='P1').length}</b><span>${p3t('Critical priority','Prioritate critică')}</span></article></section><section class="p3Panel"><header><h3>${p3t('Work queue','Coada de lucru')}</h3></header><div class="p3Table"><div class="p3Head"><span>${p3t('Record','Înregistrare')}</span><span>${p3t('Title','Titlu')}</span><span>${p3t('Priority','Prioritate')}</span><span>${p3t('Status','Stare')}</span><span>${p3t('Assignment','Alocare')}</span></div>${data.work.map(x=>`<button class="p3Row" data-work-type="${x.type}" data-work-id="${p3e(x.id)}"><span class="mono">${p3e(x.id)}</span><strong>${p3e(x.title)}</strong>${badge(x.priority)}${badge(x.status)}<span>${p3e(x.assignee||x.assignmentGroup||'—')}</span></button>`).join('')||`<p class="p3Empty">${p3t('Your queue is clear.','Coada dumneavoastră este liberă.')}</p>`}</div></section><section class="p3Panel"><header><h3>${p3t('Approval queue','Coada de aprobări')}</h3></header><div class="p3Approvals">${data.approvals.map(a=>`<article data-approval="${a.id}"><div><b>${p3e(a.recordType)} ${p3e(a.recordId)}</b><span>${p3e(a.stage)} · ${p3fmt(a.requestedAt)}</span></div><button data-decision="Approved">${p3t('Approve','Aprobă')}</button><button class="danger" data-decision="Rejected">${p3t('Reject','Respinge')}</button></article>`).join('')||`<p class="p3Empty">${p3t('No approvals awaiting a decision.','Nu există aprobări care așteaptă o decizie.')}</p>`}</div></section></div>`;
 w.querySelectorAll('[data-work-id]').forEach(b=>b.onclick=()=>{p3deactivate();const side=[...document.querySelectorAll('.app aside nav button')].find(n=>(n.textContent||'').includes(b.dataset.workType==='Incident'?'Incident':'Request'));side?.click();setTimeout(()=>{const row=[...document.querySelectorAll('.trow')].find(r=>r.querySelector('.mono')?.textContent.trim()===b.dataset.workId);row?.click()},300)});
 w.querySelectorAll('[data-decision]').forEach(b=>b.onclick=async()=>{await p3api(`/api/approvals/${b.closest('[data-approval]').dataset.approval}/decision`,{method:'POST',body:JSON.stringify({status:b.dataset.decision})});openMyWork()});
 }catch(e){w.innerHTML=`<div class="p3Shell"><section class="p3Hero"><h2>${p3t('My Work unavailable','Activitatea mea nu este disponibilă')}</h2><p>${p3e(e.message)}</p></section></div>`}
}
async function enhanceWorkflow(back){
 if(back.dataset.phase3)return;back.dataset.phase3='1';const title=back.querySelector('h2')?.textContent||'',match=title.match(/(INC|REQ)\d+/);if(!match)return;const id=match[0],kind=id.startsWith('INC')?'incidents':'requests';
 const comments=await p3api(`/api/${kind}/${id}/comments`).catch(()=>[]),body=back.querySelector('.p2Body');if(!body)return;
 const panel=document.createElement('section');panel.className='p3RecordPanel';panel.innerHTML=`<div><h3>${p3t('Comments and work notes','Comentarii și note de lucru')}</h3><div class="p3Comments">${comments.map(c=>`<article><b>${p3e(c.comment_type)}</b><span>${p3e(c.author)} · ${p3fmt(c.created_at)}</span><p>${p3e(c.body)}</p></article>`).join('')||`<p>${p3t('No comments yet.','Nu există încă comentarii.')}</p>`}</div></div><form><label>${p3t('Type','Tip')}<select name="commentType"><option>Work note</option><option>Comment</option><option>Resolution note</option></select></label><label>${p3t('Add note','Adaugă notă')}<textarea name="body" required></textarea></label><button class="primary">${p3t('Add to activity','Adaugă la activitate')}</button></form>${kind==='incidents'?`<div class="p3Escalate"><h3>${p3t('Incident control','Control incident')}</h3><button type="button" data-escalate>${p3t('Escalate','Escaladează')}</button><button type="button" class="danger" data-major>${p3t('Declare major incident','Declară incident major')}</button></div>`:`<div class="p3Escalate"><h3>${p3t('Request approval','Aprobarea solicitării')}</h3><button type="button" data-request-approval>${p3t('Request approval','Solicită aprobarea')}</button></div>`}`;
 body.append(panel);panel.querySelector('form').onsubmit=async e=>{e.preventDefault();await p3api(`/api/${kind}/${id}/comments`,{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});back.dataset.phase3='';panel.remove();enhanceWorkflow(back)};
 panel.querySelector('[data-escalate]')?.addEventListener('click',async()=>{await p3api(`/api/incidents/${id}/escalate`,{method:'POST',body:JSON.stringify({reason:'Escalated from incident workspace'})});location.reload()});
 panel.querySelector('[data-major]')?.addEventListener('click',async()=>{await p3api(`/api/incidents/${id}/escalate`,{method:'POST',body:JSON.stringify({majorIncident:true,reason:'Major incident declared'})});location.reload()});
 panel.querySelector('[data-request-approval]')?.addEventListener('click',async()=>{await p3api('/api/approvals',{method:'POST',body:JSON.stringify({recordType:'Request',recordId:id})});alert(p3t('Approval requested.','Aprobarea a fost solicitată.'))});
}
const observer=new MutationObserver(()=>document.querySelectorAll('.p2Fullscreen').forEach(back=>enhanceWorkflow(back).catch(()=>{})));observer.observe(document.body,{childList:true,subtree:true});
document.addEventListener('click',e=>{const b=e.target.closest('.app aside nav button');if(b&&document.querySelector('.app main')?.classList.contains('phase3Active'))p3deactivate()},true);
document.addEventListener('click',async e=>{const link=e.target.closest('.p3HeroActions a');if(!link)return;e.preventDefault();try{const response=await fetch(link.getAttribute('href'),{headers:{Authorization:`Bearer ${p3token()}`}});if(!response.ok)throw new Error(`HTTP ${response.status}`);const blob=await response.blob(),url=URL.createObjectURL(blob),download=document.createElement('a');download.href=url;download.download=(response.headers.get('content-disposition')?.match(/filename="([^"]+)"/)||[])[1]||'coreops-export.csv';download.click();URL.revokeObjectURL(url)}catch(error){alert(error.message)}},true);
window.CoreOpsPhase3={openMyWork};
