import type {Express} from 'express';
type Roles=(...roles:any[])=>any;
const txt=(v:any,n=2000)=>String(v??'').trim().slice(0,n);
export async function ensurePhase5V27(pool:any){await pool.query(`
 CREATE TABLE IF NOT EXISTS operational_risks(id BIGSERIAL PRIMARY KEY,number TEXT UNIQUE,title TEXT NOT NULL,description TEXT DEFAULT '',category TEXT DEFAULT 'Operational',likelihood INTEGER NOT NULL DEFAULT 3,impact INTEGER NOT NULL DEFAULT 3,score INTEGER GENERATED ALWAYS AS (likelihood*impact) STORED,owner TEXT DEFAULT '',treatment TEXT DEFAULT '',status VARCHAR(30) NOT NULL DEFAULT 'Open',review_date DATE,site_id INTEGER REFERENCES sites(id) ON DELETE SET NULL,asset_id INTEGER REFERENCES assets(id) ON DELETE SET NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS maintenance_schedules(id BIGSERIAL PRIMARY KEY,title TEXT NOT NULL,asset_id INTEGER REFERENCES assets(id) ON DELETE CASCADE,site_id INTEGER REFERENCES sites(id) ON DELETE CASCADE,frequency_days INTEGER NOT NULL DEFAULT 90,last_completed_at TIMESTAMPTZ,next_due_at TIMESTAMPTZ NOT NULL,owner TEXT DEFAULT '',instructions TEXT DEFAULT '',status VARCHAR(30) NOT NULL DEFAULT 'Scheduled',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS supplier_contracts(id BIGSERIAL PRIMARY KEY,reference TEXT UNIQUE,name TEXT NOT NULL,supplier TEXT NOT NULL,contract_type TEXT DEFAULT 'Support',owner TEXT DEFAULT '',start_date DATE,end_date DATE,annual_value NUMERIC(14,2) NOT NULL DEFAULT 0,currency VARCHAR(8) DEFAULT 'GBP',notice_days INTEGER NOT NULL DEFAULT 90,status VARCHAR(30) NOT NULL DEFAULT 'Active',notes TEXT DEFAULT '',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS asset_contracts(asset_id INTEGER NOT NULL REFERENCES assets(id) ON DELETE CASCADE,contract_id BIGINT NOT NULL REFERENCES supplier_contracts(id) ON DELETE CASCADE,warranty_end DATE,support_level TEXT DEFAULT '',PRIMARY KEY(asset_id,contract_id));
 CREATE TABLE IF NOT EXISTS continuity_plans(id BIGSERIAL PRIMARY KEY,name TEXT NOT NULL,service_name TEXT NOT NULL,owner TEXT DEFAULT '',rto_minutes INTEGER NOT NULL DEFAULT 240,rpo_minutes INTEGER NOT NULL DEFAULT 60,criticality VARCHAR(20) DEFAULT 'High',status VARCHAR(30) NOT NULL DEFAULT 'Draft',last_tested_at TIMESTAMPTZ,next_test_at TIMESTAMPTZ,recovery_strategy TEXT DEFAULT '',dependencies TEXT DEFAULT '',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS recurring_tasks(id BIGSERIAL PRIMARY KEY,title TEXT NOT NULL,task_type TEXT DEFAULT 'Operational',owner_group TEXT DEFAULT '',frequency_days INTEGER NOT NULL DEFAULT 30,next_due_at TIMESTAMPTZ NOT NULL,status VARCHAR(30) NOT NULL DEFAULT 'Active',instructions TEXT DEFAULT '',last_generated_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
`)}
export function registerPhase5V27(app:Express,pool:any,requireRoles:Roles){
 const write=requireRoles('Administrator','Service Desk','Engineer','Infrastructure','Auditor'),admin=requireRoles('Administrator');
 app.get('/api/governance/summary',async(_req:any,res:any,next:any)=>{try{const r=await pool.query(`SELECT (SELECT COUNT(*) FROM operational_risks WHERE status='Open')::int open_risks,(SELECT COUNT(*) FROM operational_risks WHERE status='Open' AND score>=15)::int high_risks,(SELECT COUNT(*) FROM maintenance_schedules WHERE status='Scheduled' AND next_due_at<NOW())::int overdue_maintenance,(SELECT COUNT(*) FROM supplier_contracts WHERE status='Active' AND end_date<=CURRENT_DATE+INTERVAL '90 days')::int contracts_expiring,(SELECT COUNT(*) FROM continuity_plans WHERE next_test_at<NOW() OR last_tested_at IS NULL)::int continuity_tests_due,(SELECT COUNT(*) FROM recurring_tasks WHERE status='Active' AND next_due_at<NOW())::int recurring_tasks_due`);res.json({...r.rows[0],generatedAt:new Date().toISOString()})}catch(e){next(e)}});
 app.get('/api/governance/risks',async(_req:any,res:any,next:any)=>{try{res.json((await pool.query(`SELECT r.*,s.name site_name,a.name asset_name FROM operational_risks r LEFT JOIN sites s ON s.id=r.site_id LEFT JOIN assets a ON a.id=r.asset_id ORDER BY r.score DESC,r.review_date`)).rows)}catch(e){next(e)}});
 app.post('/api/governance/risks',write,async(req:any,res:any,next:any)=>{try{const b=req.body||{};if(!txt(b.title))return res.status(400).json({error:'title required'});const seq=Number((await pool.query('SELECT COALESCE(MAX(id),0)+1 next FROM operational_risks')).rows[0].next),number=`RSK${String(seq).padStart(6,'0')}`;const r=await pool.query(`INSERT INTO operational_risks(number,title,description,category,likelihood,impact,owner,treatment,status,review_date,site_id,asset_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING *`,[number,txt(b.title,300),txt(b.description),txt(b.category,100)||'Operational',Math.max(1,Math.min(5,Number(b.likelihood||3))),Math.max(1,Math.min(5,Number(b.impact||3))),txt(b.owner,200),txt(b.treatment),txt(b.status,30)||'Open',b.reviewDate||null,b.siteId||null,b.assetId||null]);res.status(201).json(r.rows[0])}catch(e){next(e)}});
 app.patch('/api/governance/risks/:id',write,async(req:any,res:any,next:any)=>{try{const old=(await pool.query('SELECT * FROM operational_risks WHERE id=$1',[req.params.id])).rows[0];if(!old)return res.status(404).json({error:'risk not found'});const b=req.body||{};const r=await pool.query(`UPDATE operational_risks SET title=$1,description=$2,category=$3,likelihood=$4,impact=$5,owner=$6,treatment=$7,status=$8,review_date=$9,updated_at=NOW() WHERE id=$10 RETURNING *`,[txt(b.title)||old.title,b.description===undefined?old.description:txt(b.description),txt(b.category)||old.category,Number(b.likelihood||old.likelihood),Number(b.impact||old.impact),b.owner===undefined?old.owner:txt(b.owner),b.treatment===undefined?old.treatment:txt(b.treatment),txt(b.status)||old.status,b.reviewDate??old.review_date,req.params.id]);res.json(r.rows[0])}catch(e){next(e)}});
 app.get('/api/governance/maintenance',async(_req:any,res:any,next:any)=>{try{res.json((await pool.query(`SELECT m.*,a.asset_number,a.name asset_name,s.name site_name FROM maintenance_schedules m LEFT JOIN assets a ON a.id=m.asset_id LEFT JOIN sites s ON s.id=m.site_id ORDER BY m.next_due_at`)).rows)}catch(e){next(e)}});
 app.post('/api/governance/maintenance',write,async(req:any,res:any,next:any)=>{try{const b=req.body||{};const r=await pool.query(`INSERT INTO maintenance_schedules(title,asset_id,site_id,frequency_days,next_due_at,owner,instructions) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *`,[txt(b.title,300),b.assetId||null,b.siteId||null,Math.max(1,Number(b.frequencyDays||90)),b.nextDueAt||new Date(),txt(b.owner),txt(b.instructions)]);res.status(201).json(r.rows[0])}catch(e){next(e)}});
 app.post('/api/governance/maintenance/:id/complete',write,async(req:any,res:any,next:any)=>{try{const r=await pool.query(`UPDATE maintenance_schedules SET last_completed_at=NOW(),next_due_at=NOW()+make_interval(days=>frequency_days),status='Scheduled',updated_at=NOW() WHERE id=$1 RETURNING *`,[req.params.id]);if(!r.rows[0])return res.status(404).json({error:'schedule not found'});res.json(r.rows[0])}catch(e){next(e)}});
 app.get('/api/governance/contracts',async(_req:any,res:any,next:any)=>{try{res.json((await pool.query(`SELECT *,end_date-CURRENT_DATE days_remaining FROM supplier_contracts ORDER BY end_date NULLS LAST`)).rows)}catch(e){next(e)}});
 app.post('/api/governance/contracts',admin,async(req:any,res:any,next:any)=>{try{const b=req.body||{};const r=await pool.query(`INSERT INTO supplier_contracts(reference,name,supplier,contract_type,owner,start_date,end_date,annual_value,currency,notice_days,notes) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING *`,[txt(b.reference,80),txt(b.name,300),txt(b.supplier,300),txt(b.contractType,100)||'Support',txt(b.owner),b.startDate||null,b.endDate||null,Number(b.annualValue||0),txt(b.currency,8)||'GBP',Number(b.noticeDays||90),txt(b.notes)]);res.status(201).json(r.rows[0])}catch(e){next(e)}});
 app.get('/api/governance/continuity',async(_req:any,res:any,next:any)=>{try{res.json((await pool.query('SELECT * FROM continuity_plans ORDER BY criticality,next_test_at')).rows)}catch(e){next(e)}});
 app.post('/api/governance/continuity',admin,async(req:any,res:any,next:any)=>{try{const b=req.body||{};const r=await pool.query(`INSERT INTO continuity_plans(name,service_name,owner,rto_minutes,rpo_minutes,criticality,status,next_test_at,recovery_strategy,dependencies) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *`,[txt(b.name),txt(b.serviceName),txt(b.owner),Number(b.rtoMinutes||240),Number(b.rpoMinutes||60),txt(b.criticality,20)||'High',txt(b.status,30)||'Draft',b.nextTestAt||null,txt(b.recoveryStrategy),txt(b.dependencies)]);res.status(201).json(r.rows[0])}catch(e){next(e)}});
 app.post('/api/governance/continuity/:id/test',write,async(req:any,res:any,next:any)=>{try{const r=await pool.query(`UPDATE continuity_plans SET last_tested_at=NOW(),next_test_at=NOW()+INTERVAL '180 days',status='Current',updated_at=NOW() WHERE id=$1 RETURNING *`,[req.params.id]);if(!r.rows[0])return res.status(404).json({error:'plan not found'});res.json(r.rows[0])}catch(e){next(e)}});
 app.get('/api/governance/tasks',async(_req:any,res:any,next:any)=>{try{res.json((await pool.query('SELECT * FROM recurring_tasks ORDER BY next_due_at')).rows)}catch(e){next(e)}});
 app.post('/api/governance/tasks/generate',admin,async(req:any,res:any,next:any)=>{try{const due=(await pool.query(`SELECT * FROM recurring_tasks WHERE status='Active' AND next_due_at<=NOW()`)).rows;for(const task of due){const seq=Number((await pool.query('SELECT COALESCE(MAX(id),0)+1 next FROM service_requests')).rows[0].next),number=`REQ${String(seq).padStart(6,'0')}`;await pool.query(`INSERT INTO service_requests(number,title,description,status,priority,requested_for,assignment_group) VALUES($1,$2,$3,'Open','P3','Operations',$4)`,[number,task.title,task.instructions,task.owner_group||'Service Desk']);await pool.query(`UPDATE recurring_tasks SET last_generated_at=NOW(),next_due_at=NOW()+make_interval(days=>frequency_days),updated_at=NOW() WHERE id=$1`,[task.id])}res.json({generated:due.length})}catch(e){next(e)}});
}
