import type {Express} from 'express';
type Roles=(...roles:any[])=>any;
const clean=(value:any,max=2000)=>String(value??'').trim().slice(0,max);

export async function ensurePhase9V34(pool:any){await pool.query(`
 CREATE TABLE IF NOT EXISTS assignment_groups(id BIGSERIAL PRIMARY KEY,name VARCHAR(120) UNIQUE NOT NULL,description TEXT DEFAULT '',manager TEXT DEFAULT '',active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS assignment_group_members(group_id BIGINT NOT NULL REFERENCES assignment_groups(id) ON DELETE CASCADE,user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),PRIMARY KEY(group_id,user_id));
 CREATE TABLE IF NOT EXISTS record_watchers(id BIGSERIAL PRIMARY KEY,record_type VARCHAR(30) NOT NULL,record_id VARCHAR(80) NOT NULL,watcher_email TEXT NOT NULL,watcher_name TEXT DEFAULT '',added_by TEXT DEFAULT '',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(record_type,record_id,watcher_email));
 CREATE INDEX IF NOT EXISTS idx_record_watchers_record ON record_watchers(record_type,record_id);
 CREATE TABLE IF NOT EXISTS record_attachments(id BIGSERIAL PRIMARY KEY,record_type VARCHAR(30) NOT NULL,record_id VARCHAR(80) NOT NULL,file_name TEXT NOT NULL,file_url TEXT NOT NULL DEFAULT '',content_type VARCHAR(120) DEFAULT '',size_bytes BIGINT NOT NULL DEFAULT 0,description TEXT DEFAULT '',uploaded_by TEXT DEFAULT '',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
 CREATE INDEX IF NOT EXISTS idx_record_attachments_record ON record_attachments(record_type,record_id,created_at DESC);
 CREATE TABLE IF NOT EXISTS response_templates(id BIGSERIAL PRIMARY KEY,name VARCHAR(160) UNIQUE NOT NULL,record_type VARCHAR(30) NOT NULL DEFAULT 'Any',category VARCHAR(80) DEFAULT 'General',body TEXT NOT NULL,active BOOLEAN NOT NULL DEFAULT TRUE,created_by TEXT DEFAULT '',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS saved_views(id BIGSERIAL PRIMARY KEY,user_email TEXT NOT NULL,name VARCHAR(120) NOT NULL,record_type VARCHAR(30) NOT NULL,filters JSONB NOT NULL DEFAULT '{}'::jsonb,is_default BOOLEAN NOT NULL DEFAULT FALSE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(user_email,name,record_type));
 INSERT INTO assignment_groups(name,description) VALUES('Service Desk','First-line service management'),('Infrastructure','Infrastructure operations'),('Networks','Network operations'),('Deskside','End-user computing') ON CONFLICT(name) DO NOTHING;
 INSERT INTO response_templates(name,record_type,category,body,created_by) VALUES('Request more information','Any','Customer update','Please provide the additional information required so we can continue this request.','System'),('Work in progress','Any','Status update','Your record is being investigated. We will provide another update when more information is available.','System'),('Resolution confirmation','Incident','Resolution','The issue has been resolved. Please confirm that service is operating normally.','System') ON CONFLICT(name) DO NOTHING;
 DO $$ DECLARE table_name TEXT; BEGIN FOREACH table_name IN ARRAY ARRAY['assignment_groups','assignment_group_members','record_watchers','record_attachments','response_templates','saved_views'] LOOP EXECUTE format('DROP TRIGGER IF EXISTS coreops_audit_trigger ON %I',table_name);EXECUTE format('CREATE TRIGGER coreops_audit_trigger AFTER INSERT OR UPDATE OR DELETE ON %I FOR EACH ROW WHEN (OLD IS DISTINCT FROM NEW) EXECUTE FUNCTION coreops_record_audit()',table_name);END LOOP;END $$;
 INSERT INTO schema_migrations(migration_key,description) VALUES('034-phase9','Service Desk productivity and native record workspace') ON CONFLICT(migration_key) DO NOTHING;
`)}

export function registerPhase9V34(app:Express,pool:any,requireRoles:Roles){
 const service=requireRoles('Administrator','Service Desk','Engineer','Infrastructure'),admin=requireRoles('Administrator');
 const actor=(req:any)=>req.authUser?.email||req.authUser?.name||'Core Ops';
 const kind=(value:string)=>value==='incidents'?'Incident':value==='requests'?'Request':'';
 app.get('/api/service-desk/groups',async(_req:any,res:any,next:any)=>{try{res.json((await pool.query(`SELECT g.*,COUNT(m.user_id)::int member_count FROM assignment_groups g LEFT JOIN assignment_group_members m ON m.group_id=g.id WHERE g.active=TRUE GROUP BY g.id ORDER BY g.name`)).rows)}catch(e){next(e)}});
 app.post('/api/service-desk/groups',admin,async(req:any,res:any,next:any)=>{try{const r=await pool.query(`INSERT INTO assignment_groups(name,description,manager) VALUES($1,$2,$3) RETURNING *`,[clean(req.body?.name,120),clean(req.body?.description),clean(req.body?.manager,200)]);res.status(201).json(r.rows[0])}catch(e){next(e)}});
 app.get('/api/service-desk/templates',async(req:any,res:any,next:any)=>{try{res.json((await pool.query(`SELECT * FROM response_templates WHERE active=TRUE AND record_type IN ('Any',$1) ORDER BY category,name`,[clean(req.query.recordType,30)||'Any'])).rows)}catch(e){next(e)}});
 app.post('/api/service-desk/templates',admin,async(req:any,res:any,next:any)=>{try{const r=await pool.query(`INSERT INTO response_templates(name,record_type,category,body,created_by) VALUES($1,$2,$3,$4,$5) RETURNING *`,[clean(req.body?.name,160),clean(req.body?.recordType,30)||'Any',clean(req.body?.category,80)||'General',clean(req.body?.body),actor(req)]);res.status(201).json(r.rows[0])}catch(e){next(e)}});
 app.get('/api/service-desk/views/:recordType',async(req:any,res:any,next:any)=>{try{res.json((await pool.query(`SELECT * FROM saved_views WHERE user_email=$1 AND record_type=$2 ORDER BY is_default DESC,name`,[actor(req),clean(req.params.recordType,30)])).rows)}catch(e){next(e)}});
 app.post('/api/service-desk/views',async(req:any,res:any,next:any)=>{try{const b=req.body||{};const r=await pool.query(`INSERT INTO saved_views(user_email,name,record_type,filters,is_default) VALUES($1,$2,$3,$4,$5) ON CONFLICT(user_email,name,record_type) DO UPDATE SET filters=EXCLUDED.filters,is_default=EXCLUDED.is_default,updated_at=NOW() RETURNING *`,[actor(req),clean(b.name,120),clean(b.recordType,30),JSON.stringify(b.filters||{}),Boolean(b.isDefault)]);res.status(201).json(r.rows[0])}catch(e){next(e)}});
 app.get('/api/:recordType/:id/collaboration',async(req:any,res:any,next:any)=>{try{const type=kind(req.params.recordType);if(!type)return res.status(404).json({error:'record type not found'});const [comments,watchers,attachments,templates]=await Promise.all([pool.query(`SELECT * FROM record_comments WHERE record_type=$1 AND record_id=$2 ORDER BY created_at DESC`,[type,req.params.id]),pool.query(`SELECT * FROM record_watchers WHERE record_type=$1 AND record_id=$2 ORDER BY watcher_name,watcher_email`,[type,req.params.id]),pool.query(`SELECT * FROM record_attachments WHERE record_type=$1 AND record_id=$2 ORDER BY created_at DESC`,[type,req.params.id]),pool.query(`SELECT * FROM response_templates WHERE active=TRUE AND record_type IN ('Any',$1) ORDER BY category,name`,[type])]);res.json({comments:comments.rows,watchers:watchers.rows,attachments:attachments.rows,templates:templates.rows})}catch(e){next(e)}});
 app.post('/api/:recordType/:id/watchers',service,async(req:any,res:any,next:any)=>{try{const type=kind(req.params.recordType),email=clean(req.body?.email,300).toLowerCase();if(!type||!email.includes('@'))return res.status(400).json({error:'valid record type and watcher email required'});const r=await pool.query(`INSERT INTO record_watchers(record_type,record_id,watcher_email,watcher_name,added_by) VALUES($1,$2,$3,$4,$5) ON CONFLICT(record_type,record_id,watcher_email) DO UPDATE SET watcher_name=EXCLUDED.watcher_name RETURNING *`,[type,req.params.id,email,clean(req.body?.name,200),actor(req)]);res.status(201).json(r.rows[0])}catch(e){next(e)}});
 app.delete('/api/:recordType/:id/watchers/:watcherId',service,async(req:any,res:any,next:any)=>{try{const type=kind(req.params.recordType);const r=await pool.query(`DELETE FROM record_watchers WHERE id=$1 AND record_type=$2 AND record_id=$3 RETURNING id`,[req.params.watcherId,type,req.params.id]);if(!r.rows[0])return res.status(404).json({error:'watcher not found'});res.json({ok:true})}catch(e){next(e)}});
 app.post('/api/:recordType/:id/attachments',service,async(req:any,res:any,next:any)=>{try{const type=kind(req.params.recordType),b=req.body||{};if(!type||!clean(b.fileName,500))return res.status(400).json({error:'file name required'});const r=await pool.query(`INSERT INTO record_attachments(record_type,record_id,file_name,file_url,content_type,size_bytes,description,uploaded_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *`,[type,req.params.id,clean(b.fileName,500),clean(b.fileUrl,2000),clean(b.contentType,120),Math.max(0,Number(b.sizeBytes||0)),clean(b.description),actor(req)]);res.status(201).json(r.rows[0])}catch(e){next(e)}});
 app.patch('/api/:recordType/:id/assignment',service,async(req:any,res:any,next:any)=>{try{const type=kind(req.params.recordType),table=type==='Incident'?'incidents':type==='Request'?'service_requests':'';if(!table)return res.status(404).json({error:'record type not found'});const r=await pool.query(`UPDATE ${table} SET assignment_group=$1,assignee=$2,updated_at=NOW() WHERE number=$3 RETURNING *`,[clean(req.body?.assignmentGroup,120)||'Service Desk',clean(req.body?.assignee,200),req.params.id]);if(!r.rows[0])return res.status(404).json({error:'record not found'});await pool.query(`INSERT INTO workflow_history(record_type,record_id,action,detail,actor) VALUES($1,$2,'Assignment updated',$3,$4)`,[type,req.params.id,`${r.rows[0].assignment_group} / ${r.rows[0].assignee||'Unassigned'}`,actor(req)]);res.json(r.rows[0])}catch(e){next(e)}});
}
