import type {Express} from 'express';
type Roles=(...roles:any[])=>any;
const text=(v:any,n=2000)=>String(v??'').trim().slice(0,n);

export async function ensurePhase2V24(pool:any){await pool.query(`
 ALTER TABLE incidents ADD COLUMN IF NOT EXISTS assignee TEXT DEFAULT '';
 ALTER TABLE incidents ADD COLUMN IF NOT EXISTS category TEXT DEFAULT 'Service';
 ALTER TABLE incidents ADD COLUMN IF NOT EXISTS impact VARCHAR(20) DEFAULT 'Medium';
 ALTER TABLE incidents ADD COLUMN IF NOT EXISTS urgency VARCHAR(20) DEFAULT 'Medium';
 ALTER TABLE incidents ADD COLUMN IF NOT EXISTS resolution TEXT DEFAULT '';
 ALTER TABLE incidents ADD COLUMN IF NOT EXISTS resolved_at TIMESTAMPTZ;
 ALTER TABLE service_requests ADD COLUMN IF NOT EXISTS description TEXT DEFAULT '';
 ALTER TABLE service_requests ADD COLUMN IF NOT EXISTS priority VARCHAR(10) DEFAULT 'P3';
 ALTER TABLE service_requests ADD COLUMN IF NOT EXISTS assignment_group TEXT DEFAULT 'Service Desk';
 ALTER TABLE service_requests ADD COLUMN IF NOT EXISTS assignee TEXT DEFAULT '';
 ALTER TABLE service_requests ADD COLUMN IF NOT EXISTS due_at TIMESTAMPTZ;
 ALTER TABLE service_requests ADD COLUMN IF NOT EXISTS completed_at TIMESTAMPTZ;
 ALTER TABLE service_requests ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
 ALTER TABLE changes ADD COLUMN IF NOT EXISTS site_id INTEGER REFERENCES sites(id) ON DELETE SET NULL;
 ALTER TABLE changes ADD COLUMN IF NOT EXISTS asset_id INTEGER REFERENCES assets(id) ON DELETE SET NULL;
 ALTER TABLE assets ADD COLUMN IF NOT EXISTS rack_id BIGINT REFERENCES racks(id) ON DELETE SET NULL;
 ALTER TABLE assets ADD COLUMN IF NOT EXISTS equipment_id BIGINT;
 ALTER TABLE assets ADD COLUMN IF NOT EXISTS criticality VARCHAR(20) DEFAULT 'Medium';
 ALTER TABLE assets ADD COLUMN IF NOT EXISTS lifecycle_state VARCHAR(30) DEFAULT 'In Service';
 ALTER TABLE assets ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
 CREATE TABLE IF NOT EXISTS problem_incidents(problem_id BIGINT NOT NULL REFERENCES problems(id) ON DELETE CASCADE,incident_id INTEGER NOT NULL REFERENCES incidents(id) ON DELETE CASCADE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),PRIMARY KEY(problem_id,incident_id));
 CREATE TABLE IF NOT EXISTS asset_relationships(id BIGSERIAL PRIMARY KEY,parent_asset_id INTEGER NOT NULL REFERENCES assets(id) ON DELETE CASCADE,child_asset_id INTEGER NOT NULL REFERENCES assets(id) ON DELETE CASCADE,relationship_type VARCHAR(50) NOT NULL DEFAULT 'Depends on',notes TEXT DEFAULT '',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(parent_asset_id,child_asset_id,relationship_type),CHECK(parent_asset_id<>child_asset_id));
 CREATE TABLE IF NOT EXISTS workflow_history(id BIGSERIAL PRIMARY KEY,record_type VARCHAR(20) NOT NULL,record_id TEXT NOT NULL,action VARCHAR(80) NOT NULL,detail TEXT DEFAULT '',actor TEXT DEFAULT '',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
 CREATE INDEX IF NOT EXISTS idx_workflow_history_record ON workflow_history(record_type,record_id,created_at DESC);
 CREATE TABLE IF NOT EXISTS platform_settings(setting_key TEXT PRIMARY KEY,setting_value JSONB NOT NULL DEFAULT '{}'::jsonb,updated_by TEXT DEFAULT '',updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
 CREATE OR REPLACE FUNCTION coreops_attach_incident_sla() RETURNS trigger AS $$
 DECLARE p sla_policies%ROWTYPE;
 BEGIN SELECT * INTO p FROM sla_policies WHERE enabled=TRUE AND record_type='Incident' AND priority=NEW.priority ORDER BY resolution_minutes LIMIT 1;
 IF p.id IS NOT NULL THEN INSERT INTO sla_records(policy_id,record_type,record_id,title,priority,status,started_at,response_due_at,resolution_due_at) VALUES(p.id,'Incident',NEW.number,NEW.title,NEW.priority,NEW.status,COALESCE(NEW.created_at,NOW()),COALESCE(NEW.created_at,NOW())+make_interval(mins=>p.response_minutes),COALESCE(NEW.created_at,NOW())+make_interval(mins=>p.resolution_minutes)) ON CONFLICT(record_type,record_id,policy_id) DO NOTHING; END IF; RETURN NEW; END; $$ LANGUAGE plpgsql;
 DROP TRIGGER IF EXISTS trg_coreops_incident_sla ON incidents;
 CREATE TRIGGER trg_coreops_incident_sla AFTER INSERT ON incidents FOR EACH ROW EXECUTE FUNCTION coreops_attach_incident_sla();`)}

async function attachSla(pool:any,type:'Incident'|'Request',r:any){const p=(await pool.query(`SELECT * FROM sla_policies WHERE enabled=TRUE AND record_type=$1 AND priority=$2 ORDER BY resolution_minutes LIMIT 1`,[type,r.priority||'P3'])).rows[0];if(!p)return;const started=new Date(r.created_at||r.opened_at||Date.now());await pool.query(`INSERT INTO sla_records(policy_id,record_type,record_id,title,priority,status,started_at,response_due_at,resolution_due_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(record_type,record_id,policy_id) DO NOTHING`,[p.id,type,String(r.number||r.id),r.title,r.priority,r.status,started,new Date(started.getTime()+p.response_minutes*60000),new Date(started.getTime()+p.resolution_minutes*60000)])}

export function registerPhase2V24(app:Express,pool:any,requireRoles:Roles){
 const service=requireRoles('Administrator','Service Desk','Engineer','Infrastructure'),infra=requireRoles('Administrator','Engineer','Infrastructure'),admin=requireRoles('Administrator');
 const log=(t:string,id:string,a:string,d:string,u:string)=>pool.query(`INSERT INTO workflow_history(record_type,record_id,action,detail,actor) VALUES($1,$2,$3,$4,$5)`,[t,id,a,d,u]);
 app.get('/api/incidents/:number/detail',async(req:any,res:any,next:any)=>{try{const incident=(await pool.query(`SELECT i.*,i.number id,s.response_state,s.resolution_state,s.response_due_at,s.resolution_due_at,p.name sla_policy FROM incidents i LEFT JOIN sla_records s ON s.record_type='Incident' AND s.record_id=i.number LEFT JOIN sla_policies p ON p.id=s.policy_id WHERE i.number=$1`,[req.params.number])).rows[0];if(!incident)return res.status(404).json({error:'incident not found'});const [problems,h]=await Promise.all([pool.query(`SELECT p.* FROM problems p JOIN problem_incidents x ON x.problem_id=p.id JOIN incidents i ON i.id=x.incident_id WHERE i.number=$1`,[req.params.number]),pool.query(`SELECT * FROM workflow_history WHERE record_type='Incident' AND record_id=$1 ORDER BY created_at DESC`,[req.params.number])]);res.json({incident,problems:problems.rows,history:h.rows})}catch(e){next(e)}});
 app.post('/api/incidents/:number/transition',service,async(req:any,res:any,next:any)=>{try{const status=text(req.body?.status,30),allowed=['Open','Assigned','In Progress','Pending','Resolved','Closed'];if(!allowed.includes(status))return res.status(400).json({error:'invalid incident status'});const r=await pool.query(`UPDATE incidents SET status=$1,resolution=COALESCE(NULLIF($2,''),resolution),resolved_at=CASE WHEN $1 IN ('Resolved','Closed') THEN COALESCE(resolved_at,NOW()) ELSE NULL END,updated_at=NOW() WHERE number=$3 RETURNING *`,[status,text(req.body?.resolution),req.params.number]);if(!r.rows[0])return res.status(404).json({error:'incident not found'});await log('Incident',req.params.number,`Status: ${status}`,text(req.body?.note),req.authUser?.name||'');res.json(r.rows[0])}catch(e){next(e)}});
 app.post('/api/requests',service,async(req:any,res:any,next:any)=>{try{const b=req.body||{};if(!text(b.title))return res.status(400).json({error:'title required'});const seq=Number((await pool.query('SELECT COALESCE(MAX(id),0)+1 next FROM service_requests')).rows[0].next),number=`REQ${String(seq).padStart(6,'0')}`;const r=await pool.query(`INSERT INTO service_requests(number,title,description,status,priority,requested_for,assignment_group,assignee,due_at) VALUES($1,$2,$3,'Open',$4,$5,$6,$7,$8) RETURNING *`,[number,text(b.title,300),text(b.description),text(b.priority,10)||'P3',text(b.requestedFor,200)||req.authUser?.name,text(b.assignmentGroup,100)||'Service Desk',text(b.assignee,200),b.dueAt||null]);await attachSla(pool,'Request',r.rows[0]);await log('Request',number,'Created','',req.authUser?.name||'');res.status(201).json(r.rows[0])}catch(e){next(e)}});
 app.get('/api/requests/:number/detail',async(req:any,res:any,next:any)=>{try{const record=(await pool.query(`SELECT r.*,r.number id,s.response_state,s.resolution_state,s.response_due_at,s.resolution_due_at,p.name sla_policy FROM service_requests r LEFT JOIN sla_records s ON s.record_type='Request' AND s.record_id=r.number LEFT JOIN sla_policies p ON p.id=s.policy_id WHERE r.number=$1`,[req.params.number])).rows[0];if(!record)return res.status(404).json({error:'request not found'});const h=await pool.query(`SELECT * FROM workflow_history WHERE record_type='Request' AND record_id=$1 ORDER BY created_at DESC`,[req.params.number]);res.json({request:record,history:h.rows})}catch(e){next(e)}});
 app.post('/api/requests/:number/transition',service,async(req:any,res:any,next:any)=>{try{const status=text(req.body?.status,30),allowed=['Open','Approved','In Progress','Pending','Fulfilled','Closed','Cancelled'];if(!allowed.includes(status))return res.status(400).json({error:'invalid request status'});const r=await pool.query(`UPDATE service_requests SET status=$1,completed_at=CASE WHEN $1 IN ('Fulfilled','Closed') THEN COALESCE(completed_at,NOW()) ELSE NULL END,updated_at=NOW() WHERE number=$2 RETURNING *`,[status,req.params.number]);if(!r.rows[0])return res.status(404).json({error:'request not found'});await log('Request',req.params.number,`Status: ${status}`,text(req.body?.note),req.authUser?.name||'');res.json(r.rows[0])}catch(e){next(e)}});
 app.post('/api/problems/:id/incidents',service,async(req:any,res:any,next:any)=>{try{const i=(await pool.query('SELECT id FROM incidents WHERE number=$1',[req.body?.incidentNumber])).rows[0];if(!i)return res.status(404).json({error:'incident not found'});await pool.query(`INSERT INTO problem_incidents(problem_id,incident_id) VALUES($1,$2) ON CONFLICT DO NOTHING`,[req.params.id,i.id]);res.status(201).json({ok:true})}catch(e){next(e)}});
 app.get('/api/assets/:id/detail',async(req:any,res:any,next:any)=>{try{const asset=(await pool.query(`SELECT a.*,a.id "dbId",a.asset_number id,s.name site_name,l.name location_name,r.name rack_name,re.name equipment_name FROM assets a LEFT JOIN sites s ON s.id=a.site_id LEFT JOIN locations l ON l.id=a.location_id LEFT JOIN racks r ON r.id=a.rack_id LEFT JOIN rack_equipment re ON re.id=a.equipment_id WHERE a.asset_number=$1::text OR a.id::text=$1::text`,[req.params.id])).rows[0];if(!asset)return res.status(404).json({error:'asset not found'});const rel=await pool.query(`SELECT ar.*,p.asset_number parent_number,p.name parent_name,c.asset_number child_number,c.name child_name FROM asset_relationships ar JOIN assets p ON p.id=ar.parent_asset_id JOIN assets c ON c.id=ar.child_asset_id WHERE ar.parent_asset_id=$1::integer OR ar.child_asset_id=$1::integer`,[asset.dbId]);res.json({asset,relationships:rel.rows})}catch(e){next(e)}});
 app.post('/api/assets/:id/relationships',infra,async(req:any,res:any,next:any)=>{try{const p=(await pool.query('SELECT id FROM assets WHERE asset_number=$1::text OR id::text=$1::text',[req.params.id])).rows[0],c=(await pool.query('SELECT id FROM assets WHERE asset_number=$1::text OR id::text=$1::text',[String(req.body?.relatedAssetId)])).rows[0];if(!p||!c)return res.status(404).json({error:'asset not found'});const r=await pool.query(`INSERT INTO asset_relationships(parent_asset_id,child_asset_id,relationship_type,notes) VALUES($1,$2,$3,$4) RETURNING *`,[p.id,c.id,text(req.body?.relationshipType,50)||'Depends on',text(req.body?.notes)]);res.status(201).json(r.rows[0])}catch(e){next(e)}});
 app.patch('/api/changes/:id/relationships',service,async(req:any,res:any,next:any)=>{try{const r=await pool.query(`UPDATE changes SET site_id=$1,asset_id=$2,updated_at=NOW() WHERE id=$3 RETURNING *`,[req.body?.siteId||null,req.body?.assetId||null,req.params.id]);if(!r.rows[0])return res.status(404).json({error:'change not found'});res.json(r.rows[0])}catch(e){next(e)}});
 app.get('/api/reporting/phase2',async(_req:any,res:any,next:any)=>{try{const q=await pool.query(`SELECT (SELECT COUNT(*) FROM incidents WHERE status NOT IN ('Resolved','Closed'))::int open_incidents,(SELECT COUNT(*) FROM service_requests WHERE status NOT IN ('Fulfilled','Closed','Cancelled'))::int open_requests,(SELECT COUNT(*) FROM sla_records WHERE response_state='Breached' OR resolution_state='Breached')::int sla_breaches,(SELECT COUNT(*) FROM monitoring_checks WHERE status='Down')::int services_down,(SELECT COUNT(*) FROM assets WHERE state='Operational')::int operational_assets,(SELECT COUNT(*) FROM changes WHERE status IN ('Planned','In Progress'))::int active_changes`);res.json({...q.rows[0],generatedAt:new Date().toISOString()})}catch(e){next(e)}});
 app.get('/api/administration/settings',admin,async(_req:any,res:any,next:any)=>{try{res.json((await pool.query('SELECT * FROM platform_settings ORDER BY setting_key')).rows)}catch(e){next(e)}});
 app.put('/api/administration/settings/:key',admin,async(req:any,res:any,next:any)=>{try{const r=await pool.query(`INSERT INTO platform_settings(setting_key,setting_value,updated_by) VALUES($1,$2,$3) ON CONFLICT(setting_key) DO UPDATE SET setting_value=EXCLUDED.setting_value,updated_by=EXCLUDED.updated_by,updated_at=NOW() RETURNING *`,[text(req.params.key,100),req.body?.value??{},req.authUser?.email||'']);res.json(r.rows[0])}catch(e){next(e)}});
}
