import type {Express} from 'express';
type Roles=(...roles:any[])=>any;
const text=(v:any,n=3000)=>String(v??'').trim().slice(0,n);

export async function ensurePhase4V26(pool:any){await pool.query(`
 ALTER TABLE service_requests ADD COLUMN IF NOT EXISTS catalogue_item_id BIGINT;
 ALTER TABLE service_requests ADD COLUMN IF NOT EXISTS fulfilment_data JSONB NOT NULL DEFAULT '{}'::jsonb;
 ALTER TABLE service_requests ADD COLUMN IF NOT EXISTS fulfilment_progress INTEGER NOT NULL DEFAULT 0;
 CREATE TABLE IF NOT EXISTS service_catalogue_items(
  id BIGSERIAL PRIMARY KEY,code VARCHAR(40) NOT NULL UNIQUE,name TEXT NOT NULL,description TEXT DEFAULT '',category TEXT DEFAULT 'General',
  owner_group TEXT DEFAULT 'Service Desk',default_priority VARCHAR(10) DEFAULT 'P3',approval_required BOOLEAN NOT NULL DEFAULT FALSE,
  target_days INTEGER NOT NULL DEFAULT 5,form_schema JSONB NOT NULL DEFAULT '[]'::jsonb,active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS automation_rules(
  id BIGSERIAL PRIMARY KEY,name TEXT NOT NULL,event_type VARCHAR(80) NOT NULL,conditions JSONB NOT NULL DEFAULT '{}'::jsonb,
  actions JSONB NOT NULL DEFAULT '[]'::jsonb,enabled BOOLEAN NOT NULL DEFAULT TRUE,run_count INTEGER NOT NULL DEFAULT 0,
  last_run_at TIMESTAMPTZ,created_by TEXT DEFAULT '',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS automation_runs(
  id BIGSERIAL PRIMARY KEY,rule_id BIGINT REFERENCES automation_rules(id) ON DELETE SET NULL,event_type VARCHAR(80) NOT NULL,
  record_type VARCHAR(30) DEFAULT '',record_id TEXT DEFAULT '',status VARCHAR(20) NOT NULL DEFAULT 'Completed',detail TEXT DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS change_blackout_windows(
  id BIGSERIAL PRIMARY KEY,name TEXT NOT NULL,starts_at TIMESTAMPTZ NOT NULL,ends_at TIMESTAMPTZ NOT NULL,
  reason TEXT DEFAULT '',site_id INTEGER REFERENCES sites(id) ON DELETE CASCADE,active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
 INSERT INTO service_catalogue_items(code,name,description,category,owner_group,default_priority,approval_required,target_days) VALUES
 ('ACCESS','System access','Request access to an application or shared resource.','Access','Service Desk','P3',TRUE,3),
 ('HARDWARE','New hardware','Request an approved workstation or peripheral.','Hardware','Service Desk','P3',TRUE,10),
 ('ONBOARD','New starter','Coordinate access, hardware and onboarding tasks.','People','Service Desk','P2',TRUE,5)
 ON CONFLICT(code) DO NOTHING;
`)}

export function registerPhase4V26(app:Express,pool:any,requireRoles:Roles){
 const service=requireRoles('Administrator','Service Desk','Engineer','Infrastructure'),admin=requireRoles('Administrator');
 const who=(req:any)=>req.authUser?.email||req.authUser?.name||'Core Ops';
 app.get('/api/catalogue',async(_req:any,res:any,next:any)=>{try{res.json((await pool.query(`SELECT * FROM service_catalogue_items WHERE active=TRUE ORDER BY category,name`)).rows)}catch(e){next(e)}});
 app.post('/api/catalogue',admin,async(req:any,res:any,next:any)=>{try{const b=req.body||{};if(!text(b.code,40)||!text(b.name,200))return res.status(400).json({error:'code and name required'});const r=await pool.query(`INSERT INTO service_catalogue_items(code,name,description,category,owner_group,default_priority,approval_required,target_days,form_schema) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,[text(b.code,40).toUpperCase(),text(b.name,200),text(b.description),text(b.category,100)||'General',text(b.ownerGroup,100)||'Service Desk',text(b.defaultPriority,10)||'P3',Boolean(b.approvalRequired),Math.max(1,Number(b.targetDays||5)),JSON.stringify(b.formSchema||[])]);res.status(201).json(r.rows[0])}catch(e){next(e)}});
 app.post('/api/catalogue/:id/request',service,async(req:any,res:any,next:any)=>{try{const item=(await pool.query(`SELECT * FROM service_catalogue_items WHERE id=$1 AND active=TRUE`,[req.params.id])).rows[0];if(!item)return res.status(404).json({error:'catalogue item not found'});const seq=Number((await pool.query('SELECT COALESCE(MAX(id),0)+1 next FROM service_requests')).rows[0].next),number=`REQ${String(seq).padStart(6,'0')}`,due=new Date(Date.now()+Number(item.target_days)*86400000);const r=await pool.query(`INSERT INTO service_requests(number,title,description,status,priority,requested_for,assignment_group,due_at,catalogue_item_id,fulfilment_data,approval_status) VALUES($1,$2,$3,'Open',$4,$5,$6,$7,$8,$9,$10) RETURNING *`,[number,item.name,text(req.body?.description)||item.description,item.default_priority,text(req.body?.requestedFor,200)||req.authUser?.name,item.owner_group,due,item.id,JSON.stringify(req.body?.answers||{}),item.approval_required?'Pending':'Not Required']);if(item.approval_required)await pool.query(`INSERT INTO approval_tasks(record_type,record_id,stage,requested_by) VALUES('Request',$1,'Catalogue approval',$2)`,[number,who(req)]);res.status(201).json(r.rows[0])}catch(e){next(e)}});
 app.patch('/api/requests/:number/fulfilment',service,async(req:any,res:any,next:any)=>{try{const progress=Math.max(0,Math.min(100,Number(req.body?.progress||0)));const r=await pool.query(`UPDATE service_requests SET fulfilment_progress=$1,status=CASE WHEN $1=100 THEN 'Fulfilled' WHEN $1>0 AND status IN ('Open','Approved') THEN 'In Progress' ELSE status END,completed_at=CASE WHEN $1=100 THEN NOW() ELSE completed_at END,updated_at=NOW() WHERE number=$2 RETURNING *`,[progress,req.params.number]);if(!r.rows[0])return res.status(404).json({error:'request not found'});res.json(r.rows[0])}catch(e){next(e)}});

 app.get('/api/automations',admin,async(_req:any,res:any,next:any)=>{try{const [rules,runs]=await Promise.all([pool.query('SELECT * FROM automation_rules ORDER BY name'),pool.query('SELECT * FROM automation_runs ORDER BY created_at DESC LIMIT 100')]);res.json({rules:rules.rows,runs:runs.rows})}catch(e){next(e)}});
 app.post('/api/automations',admin,async(req:any,res:any,next:any)=>{try{const b=req.body||{};if(!text(b.name)||!text(b.eventType))return res.status(400).json({error:'name and event type required'});const r=await pool.query(`INSERT INTO automation_rules(name,event_type,conditions,actions,enabled,created_by) VALUES($1,$2,$3,$4,$5,$6) RETURNING *`,[text(b.name,200),text(b.eventType,80),JSON.stringify(b.conditions||{}),JSON.stringify(b.actions||[]),b.enabled!==false,who(req)]);res.status(201).json(r.rows[0])}catch(e){next(e)}});
 app.post('/api/automations/:id/run',admin,async(req:any,res:any,next:any)=>{try{const rule=(await pool.query('SELECT * FROM automation_rules WHERE id=$1',[req.params.id])).rows[0];if(!rule)return res.status(404).json({error:'automation not found'});const recordType=text(req.body?.recordType,30),recordId=text(req.body?.recordId,80),detail=`Dry-safe execution: ${Array.isArray(rule.actions)?rule.actions.length:0} configured action(s) evaluated`;const run=(await pool.query(`INSERT INTO automation_runs(rule_id,event_type,record_type,record_id,status,detail) VALUES($1,$2,$3,$4,'Completed',$5) RETURNING *`,[rule.id,rule.event_type,recordType,recordId,detail])).rows[0];await pool.query('UPDATE automation_rules SET run_count=run_count+1,last_run_at=NOW(),updated_at=NOW() WHERE id=$1',[rule.id]);res.json(run)}catch(e){next(e)}});

 app.get('/api/changes/calendar',async(req:any,res:any,next:any)=>{try{const from=req.query.from||new Date(Date.now()-30*86400000),to=req.query.to||new Date(Date.now()+90*86400000);const [changes,blackouts]=await Promise.all([pool.query(`SELECT c.*,s.name site_name,a.name asset_name FROM changes c LEFT JOIN sites s ON s.id=c.site_id LEFT JOIN assets a ON a.id=c.asset_id WHERE c.planned_start<=$2 AND c.planned_end>=$1 ORDER BY c.planned_start`,[from,to]),pool.query(`SELECT b.*,s.name site_name FROM change_blackout_windows b LEFT JOIN sites s ON s.id=b.site_id WHERE b.active=TRUE AND b.starts_at<=$2 AND b.ends_at>=$1 ORDER BY b.starts_at`,[from,to])]);res.json({changes:changes.rows,blackouts:blackouts.rows})}catch(e){next(e)}});
 app.get('/api/changes/:id/conflicts',async(req:any,res:any,next:any)=>{try{const c=(await pool.query('SELECT * FROM changes WHERE id=$1',[req.params.id])).rows[0];if(!c)return res.status(404).json({error:'change not found'});if(!c.planned_start||!c.planned_end)return res.json({conflicts:[],blackouts:[]});const [other,blackouts]=await Promise.all([pool.query(`SELECT id,number,title,planned_start,planned_end FROM changes WHERE id<>$1 AND status NOT IN ('Completed','Cancelled') AND planned_start<$3 AND planned_end>$2 AND (site_id=$4 OR asset_id=$5)`,[c.id,c.planned_start,c.planned_end,c.site_id,c.asset_id]),pool.query(`SELECT * FROM change_blackout_windows WHERE active=TRUE AND starts_at<$2 AND ends_at>$1 AND (site_id IS NULL OR site_id=$3)`,[c.planned_start,c.planned_end,c.site_id])]);res.json({conflicts:other.rows,blackouts:blackouts.rows})}catch(e){next(e)}});
 app.post('/api/changes/blackouts',admin,async(req:any,res:any,next:any)=>{try{const r=await pool.query(`INSERT INTO change_blackout_windows(name,starts_at,ends_at,reason,site_id) VALUES($1,$2,$3,$4,$5) RETURNING *`,[text(req.body?.name,200),req.body?.startsAt,req.body?.endsAt,text(req.body?.reason),req.body?.siteId||null]);res.status(201).json(r.rows[0])}catch(e){next(e)}});

 app.get('/api/knowledge/suggest',async(req:any,res:any,next:any)=>{try{const q=text(req.query.q,200);if(q.length<2)return res.json([]);res.json((await pool.query(`SELECT number,title,summary,category FROM knowledge_articles WHERE status='Published' AND (title ILIKE $1 OR summary ILIKE $1 OR content ILIKE $1) ORDER BY CASE WHEN title ILIKE $1 THEN 0 ELSE 1 END,updated_at DESC LIMIT 10`,[`%${q}%`])).rows)}catch(e){next(e)}});
 app.get('/api/assets/:id/impact',async(req:any,res:any,next:any)=>{try{const root=(await pool.query('SELECT id,asset_number,name,type,state FROM assets WHERE asset_number=$1 OR id::text=$1',[req.params.id])).rows[0];if(!root)return res.status(404).json({error:'asset not found'});const related=(await pool.query(`WITH RECURSIVE impact AS (SELECT ar.*,1 depth FROM asset_relationships ar WHERE parent_asset_id=$1 UNION ALL SELECT ar.*,i.depth+1 FROM asset_relationships ar JOIN impact i ON ar.parent_asset_id=i.child_asset_id WHERE i.depth<5) SELECT i.depth,i.relationship_type,a.asset_number,a.name,a.type,a.state FROM impact i JOIN assets a ON a.id=i.child_asset_id ORDER BY i.depth,a.name`,[root.id])).rows;const open=(await pool.query(`SELECT number,title,priority,status FROM incidents WHERE status NOT IN ('Resolved','Closed') AND asset IN ($1,$2)`,[root.asset_number,root.name])).rows;res.json({root,related,openIncidents:open})}catch(e){next(e)}});
 app.get('/api/reporting/executive',async(_req:any,res:any,next:any)=>{try{const r=await pool.query(`SELECT (SELECT COUNT(*) FROM incidents WHERE status NOT IN ('Resolved','Closed'))::int open_incidents,(SELECT COUNT(*) FROM incidents WHERE major_incident=TRUE AND status NOT IN ('Resolved','Closed'))::int major_incidents,(SELECT COUNT(*) FROM service_requests WHERE status NOT IN ('Fulfilled','Closed','Cancelled'))::int open_requests,(SELECT COUNT(*) FROM approval_tasks WHERE status='Pending')::int pending_approvals,(SELECT COUNT(*) FROM monitoring_checks WHERE status='Down')::int services_down,(SELECT COUNT(*) FROM changes WHERE status IN ('Planned','In Progress'))::int active_changes,(SELECT COUNT(*) FROM sla_records WHERE response_state='Breached' OR resolution_state='Breached')::int sla_breaches,(SELECT COUNT(*) FROM automation_runs WHERE created_at>NOW()-INTERVAL '24 hours')::int automations_24h`);res.json({...r.rows[0],generatedAt:new Date().toISOString()})}catch(e){next(e)}});
}
