import type {Express} from 'express';
import {randomBytes,scryptSync} from 'node:crypto';
type Roles=(...roles:any[])=>any;
const clean=(v:any,n=4000)=>String(v??'').trim().slice(0,n);
const hashPassword=(password:string)=>{const salt=randomBytes(16).toString('hex');return `${salt}:${scryptSync(password,salt,64).toString('hex')}`};

export async function ensurePhase10V35(pool:any){await pool.query(`
 ALTER TABLE problems ADD COLUMN IF NOT EXISTS analysis TEXT DEFAULT '';
 ALTER TABLE problems ADD COLUMN IF NOT EXISTS known_error BOOLEAN NOT NULL DEFAULT FALSE;
 ALTER TABLE problems ADD COLUMN IF NOT EXISTS known_error_status VARCHAR(30) DEFAULT 'Not Known';
 ALTER TABLE problems ADD COLUMN IF NOT EXISTS resolved_at TIMESTAMPTZ;
 ALTER TABLE changes ADD COLUMN IF NOT EXISTS impact_score INTEGER NOT NULL DEFAULT 3;
 ALTER TABLE changes ADD COLUMN IF NOT EXISTS likelihood_score INTEGER NOT NULL DEFAULT 3;
 ALTER TABLE changes ADD COLUMN IF NOT EXISTS risk_score INTEGER NOT NULL DEFAULT 9;
 ALTER TABLE changes ADD COLUMN IF NOT EXISTS business_impact TEXT DEFAULT '';
 ALTER TABLE changes ADD COLUMN IF NOT EXISTS test_plan TEXT DEFAULT '';
 ALTER TABLE changes ADD COLUMN IF NOT EXISTS pir_outcome VARCHAR(30) DEFAULT 'Not Reviewed';
 ALTER TABLE changes ADD COLUMN IF NOT EXISTS pir_notes TEXT DEFAULT '';
 ALTER TABLE changes ADD COLUMN IF NOT EXISTS completed_at TIMESTAMPTZ;
 ALTER TABLE knowledge_articles ADD COLUMN IF NOT EXISTS version INTEGER NOT NULL DEFAULT 1;
 ALTER TABLE knowledge_articles ADD COLUMN IF NOT EXISTS review_status VARCHAR(30) DEFAULT 'Not Submitted';
 ALTER TABLE knowledge_articles ADD COLUMN IF NOT EXISTS reviewed_by TEXT DEFAULT '';
 ALTER TABLE knowledge_articles ADD COLUMN IF NOT EXISTS reviewed_at TIMESTAMPTZ;
 ALTER TABLE knowledge_articles ADD COLUMN IF NOT EXISTS expires_at TIMESTAMPTZ;
 CREATE TABLE IF NOT EXISTS change_tasks(id BIGSERIAL PRIMARY KEY,change_id BIGINT NOT NULL REFERENCES changes(id) ON DELETE CASCADE,title TEXT NOT NULL,task_type VARCHAR(30) DEFAULT 'Implementation',status VARCHAR(30) DEFAULT 'Open',owner TEXT DEFAULT '',sequence_no INTEGER NOT NULL DEFAULT 10,due_at TIMESTAMPTZ,completed_at TIMESTAMPTZ,notes TEXT DEFAULT '',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS change_cab_decisions(id BIGSERIAL PRIMARY KEY,change_id BIGINT NOT NULL REFERENCES changes(id) ON DELETE CASCADE,stage VARCHAR(80) DEFAULT 'CAB review',decision VARCHAR(30) NOT NULL,decided_by TEXT NOT NULL,decision_note TEXT DEFAULT '',decided_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS knowledge_versions(id BIGSERIAL PRIMARY KEY,article_id BIGINT NOT NULL REFERENCES knowledge_articles(id) ON DELETE CASCADE,version INTEGER NOT NULL,title TEXT NOT NULL,summary TEXT DEFAULT '',content TEXT NOT NULL,change_note TEXT DEFAULT '',created_by TEXT DEFAULT '',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(article_id,version));
 CREATE INDEX IF NOT EXISTS idx_change_tasks_change ON change_tasks(change_id,sequence_no);
 CREATE INDEX IF NOT EXISTS idx_cab_change ON change_cab_decisions(change_id,decided_at DESC);
 CREATE INDEX IF NOT EXISTS idx_knowledge_versions_article ON knowledge_versions(article_id,version DESC);
 DO $$ DECLARE table_name TEXT; BEGIN FOREACH table_name IN ARRAY ARRAY['change_tasks','change_cab_decisions','knowledge_versions'] LOOP EXECUTE format('DROP TRIGGER IF EXISTS coreops_audit_trigger ON %I',table_name);EXECUTE format('CREATE TRIGGER coreops_audit_trigger AFTER INSERT OR UPDATE OR DELETE ON %I FOR EACH ROW WHEN (OLD IS DISTINCT FROM NEW) EXECUTE FUNCTION coreops_record_audit()',table_name);END LOOP;END $$;
 INSERT INTO schema_migrations(migration_key,description) VALUES('035-phase10','Mature Change, Problem, Knowledge and access administration') ON CONFLICT(migration_key) DO NOTHING;
`)}

export function registerPhase10V35(app:Express,pool:any,requireRoles:Roles){
 const service=requireRoles('Administrator','Service Desk','Engineer','Infrastructure'),change=requireRoles('Administrator','Service Desk','Infrastructure'),admin=requireRoles('Administrator');
 const actor=(req:any)=>req.authUser?.email||req.authUser?.name||'Core Ops';
 app.get('/api/problems/:id/detail',async(req:any,res:any,next:any)=>{try{const problem=(await pool.query('SELECT * FROM problems WHERE id::text=$1::text OR number=$1::text',[req.params.id])).rows[0];if(!problem)return res.status(404).json({error:'problem not found'});const [incidents,history]=await Promise.all([pool.query(`SELECT i.* FROM problem_incidents x JOIN incidents i ON i.id=x.incident_id WHERE x.problem_id=$1 ORDER BY i.opened_at DESC`,[problem.id]),pool.query(`SELECT * FROM audit_events WHERE table_name IN ('problems','problem_incidents') AND (record_id=$1 OR after_data->>'problem_id'=$2) ORDER BY created_at DESC LIMIT 200`,[String(problem.id),String(problem.id)])]);res.json({problem,incidents:incidents.rows,history:history.rows})}catch(e){next(e)}});
 app.patch('/api/problems/:id/investigation',service,async(req:any,res:any,next:any)=>{try{const b=req.body||{};const r=await pool.query(`UPDATE problems SET analysis=$1,root_cause=$2,workaround=$3,known_error=$4,known_error_status=$5,status=$6,resolved_at=CASE WHEN $6='Closed' THEN COALESCE(resolved_at,NOW()) ELSE NULL END,updated_at=NOW() WHERE id=$7 RETURNING *`,[clean(b.analysis),clean(b.rootCause),clean(b.workaround),Boolean(b.knownError),clean(b.knownErrorStatus,30)||'Not Known',clean(b.status,30)||'Open',req.params.id]);if(!r.rows[0])return res.status(404).json({error:'problem not found'});res.json(r.rows[0])}catch(e){next(e)}});
 app.get('/api/problems/:id/suggest-incidents',async(req:any,res:any,next:any)=>{try{const p=(await pool.query('SELECT title,description FROM problems WHERE id=$1',[req.params.id])).rows[0];if(!p)return res.status(404).json({error:'problem not found'});const terms=clean(`${p.title} ${p.description}`,500).split(/\s+/).filter((x:string)=>x.length>4).slice(0,8);if(!terms.length)return res.json([]);res.json((await pool.query(`SELECT id,number,title,status,priority FROM incidents WHERE status NOT IN ('Resolved','Closed') AND (${terms.map((_:string,i:number)=>`title ILIKE $${i+1}`).join(' OR ')}) ORDER BY opened_at DESC LIMIT 20`,terms.map((x:string)=>`%${x}%`))).rows)}catch(e){next(e)}});
 app.get('/api/changes/:id/detail',async(req:any,res:any,next:any)=>{try{const item=(await pool.query(`SELECT c.*,s.name site_name,a.name asset_name FROM changes c LEFT JOIN sites s ON s.id=c.site_id LEFT JOIN assets a ON a.id=c.asset_id WHERE c.id::text=$1::text OR c.number=$1::text`,[req.params.id])).rows[0];if(!item)return res.status(404).json({error:'change not found'});const [tasks,decisions,conflicts,blackouts]=await Promise.all([pool.query('SELECT * FROM change_tasks WHERE change_id=$1 ORDER BY sequence_no,id',[item.id]),pool.query('SELECT * FROM change_cab_decisions WHERE change_id=$1 ORDER BY decided_at DESC',[item.id]),pool.query(`SELECT id,number,title,planned_start,planned_end FROM changes WHERE id<>$1 AND status NOT IN ('Completed','Cancelled') AND planned_start<$3 AND planned_end>$2 AND (site_id=$4 OR asset_id=$5)`,[item.id,item.planned_start,item.planned_end,item.site_id,item.asset_id]),pool.query(`SELECT * FROM change_blackout_windows WHERE active=TRUE AND starts_at<$2 AND ends_at>$1 AND (site_id IS NULL OR site_id=$3)`,[item.planned_start,item.planned_end,item.site_id])]);res.json({change:item,tasks:tasks.rows,decisions:decisions.rows,conflicts:conflicts.rows,blackouts:blackouts.rows})}catch(e){next(e)}});
 app.patch('/api/changes/:id/assessment',change,async(req:any,res:any,next:any)=>{try{const b=req.body||{},impact=Math.min(5,Math.max(1,Number(b.impactScore||3))),likelihood=Math.min(5,Math.max(1,Number(b.likelihoodScore||3))),score=impact*likelihood,risk=score>=20?'Critical':score>=12?'High':score>=6?'Medium':'Low';const r=await pool.query(`UPDATE changes SET impact_score=$1,likelihood_score=$2,risk_score=$3,risk=$4,business_impact=$5,test_plan=$6,updated_at=NOW() WHERE id=$7 RETURNING *`,[impact,likelihood,score,risk,clean(b.businessImpact),clean(b.testPlan),req.params.id]);if(!r.rows[0])return res.status(404).json({error:'change not found'});res.json(r.rows[0])}catch(e){next(e)}});
 app.post('/api/changes/:id/tasks',change,async(req:any,res:any,next:any)=>{try{const b=req.body||{};const r=await pool.query(`INSERT INTO change_tasks(change_id,title,task_type,owner,sequence_no,due_at,notes) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *`,[req.params.id,clean(b.title,500),clean(b.taskType,30)||'Implementation',clean(b.owner,200),Number(b.sequenceNo||10),b.dueAt||null,clean(b.notes)]);res.status(201).json(r.rows[0])}catch(e){next(e)}});
 app.patch('/api/changes/:id/tasks/:taskId',change,async(req:any,res:any,next:any)=>{try{const status=clean(req.body?.status,30);const r=await pool.query(`UPDATE change_tasks SET status=$1,completed_at=CASE WHEN $1='Completed' THEN COALESCE(completed_at,NOW()) ELSE NULL END,notes=COALESCE(NULLIF($2,''),notes),updated_at=NOW() WHERE id=$3 AND change_id=$4 RETURNING *`,[status,clean(req.body?.notes),req.params.taskId,req.params.id]);if(!r.rows[0])return res.status(404).json({error:'task not found'});res.json(r.rows[0])}catch(e){next(e)}});
 app.post('/api/changes/:id/cab',change,async(req:any,res:any,next:any)=>{try{const decision=clean(req.body?.decision,30);if(!['Approved','Rejected','Deferred'].includes(decision))return res.status(400).json({error:'valid CAB decision required'});const r=await pool.query(`INSERT INTO change_cab_decisions(change_id,stage,decision,decided_by,decision_note) VALUES($1,$2,$3,$4,$5) RETURNING *`,[req.params.id,clean(req.body?.stage,80)||'CAB review',decision,actor(req),clean(req.body?.note)]);await pool.query(`UPDATE changes SET approval_status=$1,status=CASE WHEN $1='Approved' AND status='Draft' THEN 'Planned' ELSE status END,approved_by=CASE WHEN $1='Approved' THEN $2 ELSE approved_by END,updated_at=NOW() WHERE id=$3`,[decision,actor(req),req.params.id]);res.status(201).json(r.rows[0])}catch(e){next(e)}});
 app.post('/api/changes/:id/pir',change,async(req:any,res:any,next:any)=>{try{const outcome=clean(req.body?.outcome,30);if(!['Successful','Successful with issues','Failed'].includes(outcome))return res.status(400).json({error:'valid review outcome required'});const r=await pool.query(`UPDATE changes SET pir_outcome=$1,pir_notes=$2,status='Completed',completed_at=COALESCE(completed_at,NOW()),updated_at=NOW() WHERE id=$3 RETURNING *`,[outcome,clean(req.body?.notes),req.params.id]);res.json(r.rows[0])}catch(e){next(e)}});
 app.get('/api/knowledge/:id/detail',async(req:any,res:any,next:any)=>{try{const article=(await pool.query('SELECT * FROM knowledge_articles WHERE id::text=$1::text OR number=$1::text',[req.params.id])).rows[0];if(!article)return res.status(404).json({error:'article not found'});const versions=(await pool.query('SELECT * FROM knowledge_versions WHERE article_id=$1 ORDER BY version DESC',[article.id])).rows;res.json({article,versions})}catch(e){next(e)}});
 app.post('/api/knowledge/:id/revise',service,async(req:any,res:any,next:any)=>{const client=await pool.connect();try{await client.query('BEGIN');const article=(await client.query('SELECT * FROM knowledge_articles WHERE id=$1 FOR UPDATE',[req.params.id])).rows[0];if(!article){await client.query('ROLLBACK');return res.status(404).json({error:'article not found'})}const version=Number(article.version)+1,b=req.body||{};await client.query(`INSERT INTO knowledge_versions(article_id,version,title,summary,content,change_note,created_by) VALUES($1,$2,$3,$4,$5,$6,$7)`,[article.id,article.version,article.title,article.summary,article.content,clean(b.changeNote),actor(req)]);const r=await client.query(`UPDATE knowledge_articles SET title=$1,summary=$2,content=$3,version=$4,status='Draft',review_status='Not Submitted',reviewed_by='',reviewed_at=NULL,updated_at=NOW() WHERE id=$5 RETURNING *`,[clean(b.title,500)||article.title,clean(b.summary),clean(b.content)||article.content,version,article.id]);await client.query('COMMIT');res.json(r.rows[0])}catch(e){await client.query('ROLLBACK');next(e)}finally{client.release()}});
 app.post('/api/knowledge/:id/review',service,async(req:any,res:any,next:any)=>{try{const decision=clean(req.body?.decision,30);if(!['Submitted','Approved','Rejected'].includes(decision))return res.status(400).json({error:'valid review decision required'});const r=await pool.query(`UPDATE knowledge_articles SET review_status=$1,reviewed_by=CASE WHEN $1 IN ('Approved','Rejected') THEN $2 ELSE reviewed_by END,reviewed_at=CASE WHEN $1 IN ('Approved','Rejected') THEN NOW() ELSE reviewed_at END,status=CASE WHEN $1='Approved' THEN 'Published' WHEN $1='Rejected' THEN 'Draft' ELSE status END,published_at=CASE WHEN $1='Approved' THEN COALESCE(published_at,NOW()) ELSE published_at END,expires_at=CASE WHEN $1='Approved' THEN COALESCE($3::timestamptz,NOW()+INTERVAL '365 days') ELSE expires_at END,updated_at=NOW() WHERE id=$4 RETURNING *`,[decision,actor(req),req.body?.expiresAt||null,req.params.id]);if(!r.rows[0])return res.status(404).json({error:'article not found'});res.json(r.rows[0])}catch(e){next(e)}});
 app.get('/api/knowledge/suggest/:incidentNumber',async(req:any,res:any,next:any)=>{try{const incident=(await pool.query('SELECT title,description FROM incidents WHERE number=$1',[req.params.incidentNumber])).rows[0];if(!incident)return res.status(404).json({error:'incident not found'});const terms=clean(`${incident.title} ${incident.description}`,500).split(/\s+/).filter((x:string)=>x.length>4).slice(0,8);if(!terms.length)return res.json([]);res.json((await pool.query(`SELECT id,number,title,summary,category FROM knowledge_articles WHERE status='Published' AND (${terms.map((_:string,i:number)=>`(title ILIKE $${i+1} OR summary ILIKE $${i+1})`).join(' OR ')}) ORDER BY updated_at DESC LIMIT 10`,terms.map((x:string)=>`%${x}%`))).rows)}catch(e){next(e)}});
 app.patch('/api/administration/users/:id',admin,async(req:any,res:any,next:any)=>{try{const role=clean(req.body?.role,40),roles=['Administrator','Service Desk','Engineer','Infrastructure','Auditor','Read Only'];if(role&&!roles.includes(role))return res.status(400).json({error:'invalid role'});const r=await pool.query(`UPDATE users SET name=COALESCE(NULLIF($1,''),name),role=COALESCE(NULLIF($2,''),role),active=COALESCE($3,active) WHERE id=$4 RETURNING id,email,name,role,active`,[clean(req.body?.name,200),role,req.body?.active===undefined?null:Boolean(req.body.active),req.params.id]);if(!r.rows[0])return res.status(404).json({error:'user not found'});res.json(r.rows[0])}catch(e){next(e)}});
 app.post('/api/administration/users/:id/reset-password',admin,async(req:any,res:any,next:any)=>{try{const password=String(req.body?.password||'');if(password.length<12)return res.status(400).json({error:'password must be at least 12 characters'});const r=await pool.query(`UPDATE users SET password_hash=$1 WHERE id=$2 RETURNING id,email`,[hashPassword(password),req.params.id]);if(!r.rows[0])return res.status(404).json({error:'user not found'});res.json({ok:true,user:r.rows[0]})}catch(e){next(e)}});
}
