import type {Express} from 'express';
type Roles=(...roles:any[])=>any;
const clean=(v:any,n=3000)=>String(v??'').trim().slice(0,n);
export async function ensurePhase11V37(pool:any){await pool.query(`
 ALTER TABLE assets ADD COLUMN IF NOT EXISTS purchase_date DATE;ALTER TABLE assets ADD COLUMN IF NOT EXISTS purchase_cost NUMERIC(14,2) DEFAULT 0;ALTER TABLE assets ADD COLUMN IF NOT EXISTS currency CHAR(3) DEFAULT 'GBP';ALTER TABLE assets ADD COLUMN IF NOT EXISTS warranty_end DATE;ALTER TABLE assets ADD COLUMN IF NOT EXISTS supplier TEXT DEFAULT '';ALTER TABLE assets ADD COLUMN IF NOT EXISTS cost_centre TEXT DEFAULT '';ALTER TABLE assets ADD COLUMN IF NOT EXISTS depreciation_years INTEGER DEFAULT 3;ALTER TABLE assets ADD COLUMN IF NOT EXISTS disposal_date DATE;ALTER TABLE assets ADD COLUMN IF NOT EXISTS stock_status VARCHAR(30) DEFAULT 'Deployed';ALTER TABLE assets ADD COLUMN IF NOT EXISTS data_quality_score INTEGER DEFAULT 0;
 CREATE TABLE IF NOT EXISTS software_products(id BIGSERIAL PRIMARY KEY,name TEXT NOT NULL,publisher TEXT DEFAULT '',version TEXT DEFAULT '',licence_type VARCHAR(40) DEFAULT 'Subscription',entitlement_count INTEGER NOT NULL DEFAULT 0,renewal_date DATE,cost NUMERIC(14,2) DEFAULT 0,currency CHAR(3) DEFAULT 'GBP',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(name,publisher,version));
 CREATE TABLE IF NOT EXISTS asset_software(asset_id INTEGER NOT NULL REFERENCES assets(id) ON DELETE CASCADE,software_id BIGINT NOT NULL REFERENCES software_products(id) ON DELETE CASCADE,installed_version TEXT DEFAULT '',licence_key_reference TEXT DEFAULT '',assigned_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),assigned_by TEXT DEFAULT '',PRIMARY KEY(asset_id,software_id));
 CREATE TABLE IF NOT EXISTS asset_lifecycle_events(id BIGSERIAL PRIMARY KEY,asset_id INTEGER NOT NULL REFERENCES assets(id) ON DELETE CASCADE,from_state VARCHAR(40),to_state VARCHAR(40) NOT NULL,note TEXT DEFAULT '',actor TEXT DEFAULT '',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
 CREATE INDEX IF NOT EXISTS idx_asset_lifecycle_asset ON asset_lifecycle_events(asset_id,created_at DESC);
 DO $$ DECLARE t TEXT; BEGIN FOREACH t IN ARRAY ARRAY['software_products','asset_software','asset_lifecycle_events'] LOOP EXECUTE format('DROP TRIGGER IF EXISTS coreops_audit_trigger ON %I',t);EXECUTE format('CREATE TRIGGER coreops_audit_trigger AFTER INSERT OR UPDATE OR DELETE ON %I FOR EACH ROW EXECUTE FUNCTION coreops_record_audit()',t);END LOOP;END $$;
 INSERT INTO schema_migrations(migration_key,description) VALUES('037-phase11','CMDB lifecycle, software, stockroom and data quality') ON CONFLICT(migration_key) DO NOTHING;
`)}
const score=(a:any)=>{const fields=['name','type','owner','serial_number','model','site_id','criticality','supplier','cost_centre','purchase_date','warranty_end'];return Math.round(fields.filter(k=>a[k]!==null&&String(a[k]??'').trim()!=='').length*100/fields.length)};
export function registerPhase11V37(app:Express,pool:any,requireRoles:Roles){const write=requireRoles('Administrator','Engineer','Infrastructure'),admin=requireRoles('Administrator'),actor=(r:any)=>r.authUser?.email||r.authUser?.name||'Core Ops';
 app.get('/api/cmdb/summary',async(_req:any,res:any,next:any)=>{try{const q=await pool.query(`SELECT COUNT(*)::int assets,COUNT(*) FILTER(WHERE lifecycle_state='In Service')::int in_service,COUNT(*) FILTER(WHERE stock_status='In Stock')::int in_stock,COUNT(*) FILTER(WHERE warranty_end<CURRENT_DATE)::int warranty_expired,COUNT(*) FILTER(WHERE data_quality_score<70)::int quality_attention,ROUND(AVG(data_quality_score),0)::int average_quality,(SELECT COUNT(*) FROM software_products)::int software_products,(SELECT COUNT(*) FROM asset_software)::int software_assignments FROM assets`);res.json(q.rows[0])}catch(e){next(e)}});
 app.get('/api/cmdb/assets/:id',async(req:any,res:any,next:any)=>{try{const asset=(await pool.query(`SELECT a.*,a.id db_id,a.asset_number id,s.name site_name,l.name location_name,r.name rack_name FROM assets a LEFT JOIN sites s ON s.id=a.site_id LEFT JOIN locations l ON l.id=a.location_id LEFT JOIN racks r ON r.id=a.rack_id WHERE a.asset_number=$1::text OR a.id::text=$1::text`,[req.params.id])).rows[0];if(!asset)return res.status(404).json({error:'asset not found'});const [relationships,software,lifecycle,incidents]=await Promise.all([pool.query(`SELECT ar.*,p.asset_number parent_number,p.name parent_name,c.asset_number child_number,c.name child_name FROM asset_relationships ar JOIN assets p ON p.id=ar.parent_asset_id JOIN assets c ON c.id=ar.child_asset_id WHERE ar.parent_asset_id=$1 OR ar.child_asset_id=$1`,[asset.db_id]),pool.query(`SELECT p.*,x.installed_version,x.licence_key_reference,x.assigned_at FROM asset_software x JOIN software_products p ON p.id=x.software_id WHERE x.asset_id=$1 ORDER BY p.name`,[asset.db_id]),pool.query(`SELECT * FROM asset_lifecycle_events WHERE asset_id=$1 ORDER BY created_at DESC`,[asset.db_id]),pool.query(`SELECT number,title,priority,status FROM incidents WHERE asset IN ($1,$2) ORDER BY opened_at DESC LIMIT 50`,[asset.asset_number,asset.name])]);res.json({asset,relationships:relationships.rows,software:software.rows,lifecycle:lifecycle.rows,incidents:incidents.rows})}catch(e){next(e)}});
 app.patch('/api/cmdb/assets/:id',write,async(req:any,res:any,next:any)=>{try{const b=req.body||{},current=(await pool.query(`SELECT * FROM assets WHERE asset_number=$1::text OR id::text=$1::text`,[req.params.id])).rows[0];if(!current)return res.status(404).json({error:'asset not found'});const merged={...current,...b,serial_number:b.serialNumber??current.serial_number,site_id:b.siteId??current.site_id,location_id:b.locationId??current.location_id,cost_centre:b.costCentre??current.cost_centre,purchase_date:b.purchaseDate??current.purchase_date,purchase_cost:b.purchaseCost??current.purchase_cost,warranty_end:b.warrantyEnd??current.warranty_end,depreciation_years:b.depreciationYears??current.depreciation_years,stock_status:b.stockStatus??current.stock_status};const quality=score(merged);const r=await pool.query(`UPDATE assets SET name=$1,type=$2,owner=$3,state=$4,serial_number=$5,model=$6,site_id=$7,location_id=$8,criticality=$9,purchase_date=$10,purchase_cost=$11,currency=$12,warranty_end=$13,supplier=$14,cost_centre=$15,depreciation_years=$16,stock_status=$17,data_quality_score=$18,updated_at=NOW() WHERE id=$19 RETURNING *`,[clean(b.name,160)||current.name,clean(b.type,80)||current.type,clean(b.owner,120),clean(b.state,40)||current.state,clean(b.serialNumber,160),clean(b.model,160),b.siteId||null,b.locationId||null,clean(b.criticality,20)||'Medium',b.purchaseDate||null,Number(b.purchaseCost||0),clean(b.currency,3).toUpperCase()||'GBP',b.warrantyEnd||null,clean(b.supplier,200),clean(b.costCentre,120),Math.max(1,Number(b.depreciationYears||3)),clean(b.stockStatus,30)||'Deployed',quality,current.id]);res.json(r.rows[0])}catch(e){next(e)}});
 app.post('/api/cmdb/assets/:id/lifecycle',write,async(req:any,res:any,next:any)=>{const client=await pool.connect();try{await client.query('BEGIN');const a=(await client.query(`SELECT * FROM assets WHERE asset_number=$1::text OR id::text=$1::text FOR UPDATE`,[req.params.id])).rows[0];if(!a){await client.query('ROLLBACK');return res.status(404).json({error:'asset not found'})}const to=clean(req.body?.state,40),allowed=['Planned','Ordered','In Stock','In Service','Maintenance','Retired','Disposed'];if(!allowed.includes(to)){await client.query('ROLLBACK');return res.status(400).json({error:'invalid lifecycle state'})}await client.query(`UPDATE assets SET lifecycle_state=$1,state=CASE WHEN $1 IN ('Retired','Disposed') THEN $1 ELSE state END,disposal_date=CASE WHEN $1='Disposed' THEN CURRENT_DATE ELSE disposal_date END,stock_status=CASE WHEN $1='In Stock' THEN 'In Stock' WHEN $1='In Service' THEN 'Deployed' ELSE stock_status END,updated_at=NOW() WHERE id=$2`,[to,a.id]);const r=await client.query(`INSERT INTO asset_lifecycle_events(asset_id,from_state,to_state,note,actor) VALUES($1,$2,$3,$4,$5) RETURNING *`,[a.id,a.lifecycle_state,to,clean(req.body?.note),actor(req)]);await client.query('COMMIT');res.status(201).json(r.rows[0])}catch(e){await client.query('ROLLBACK');next(e)}finally{client.release()}});
 app.get('/api/cmdb/software',async(_req:any,res:any,next:any)=>{try{res.json((await pool.query(`SELECT p.*,COUNT(x.asset_id)::int assigned_count,GREATEST(0,p.entitlement_count-COUNT(x.asset_id))::int available FROM software_products p LEFT JOIN asset_software x ON x.software_id=p.id GROUP BY p.id ORDER BY p.name`)).rows)}catch(e){next(e)}});
 app.post('/api/cmdb/software',admin,async(req:any,res:any,next:any)=>{try{const b=req.body||{};const r=await pool.query(`INSERT INTO software_products(name,publisher,version,licence_type,entitlement_count,renewal_date,cost,currency) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *`,[clean(b.name,200),clean(b.publisher,200),clean(b.version,80),clean(b.licenceType,40)||'Subscription',Math.max(0,Number(b.entitlementCount||0)),b.renewalDate||null,Number(b.cost||0),clean(b.currency,3).toUpperCase()||'GBP']);res.status(201).json(r.rows[0])}catch(e){next(e)}});
 app.post('/api/cmdb/assets/:id/software',write,async(req:any,res:any,next:any)=>{try{const a=(await pool.query(`SELECT id FROM assets WHERE asset_number=$1::text OR id::text=$1::text`,[req.params.id])).rows[0];if(!a)return res.status(404).json({error:'asset not found'});const r=await pool.query(`INSERT INTO asset_software(asset_id,software_id,installed_version,licence_key_reference,assigned_by) VALUES($1,$2,$3,$4,$5) ON CONFLICT(asset_id,software_id) DO UPDATE SET installed_version=EXCLUDED.installed_version,licence_key_reference=EXCLUDED.licence_key_reference RETURNING *`,[a.id,req.body?.softwareId,clean(req.body?.installedVersion,80),clean(req.body?.licenceKeyReference,200),actor(req)]);res.status(201).json(r.rows[0])}catch(e){next(e)}});
 app.get('/api/cmdb/quality',async(_req:any,res:any,next:any)=>{try{const assets=(await pool.query(`SELECT id,asset_number,name,type,owner,serial_number,model,site_id,criticality,supplier,cost_centre,purchase_date,warranty_end,data_quality_score FROM assets ORDER BY data_quality_score,asset_number`)).rows,duplicates=(await pool.query(`SELECT serial_number,COUNT(*)::int count,array_agg(asset_number ORDER BY asset_number) assets FROM assets WHERE serial_number<>'' GROUP BY serial_number HAVING COUNT(*)>1 ORDER BY count DESC`)).rows;res.json({assets,duplicates})}catch(e){next(e)}});
 app.post('/api/cmdb/quality/recalculate',write,async(_req:any,res:any,next:any)=>{try{const rows=(await pool.query('SELECT * FROM assets')).rows;for(const a of rows)await pool.query('UPDATE assets SET data_quality_score=$1 WHERE id=$2',[score(a),a.id]);res.json({ok:true,updated:rows.length})}catch(e){next(e)}});
 app.post('/api/cmdb/import',admin,async(req:any,res:any,next:any)=>{try{const rows=Array.isArray(req.body?.rows)?req.body.rows:[];if(rows.length>1000)return res.status(400).json({error:'maximum 1000 rows per import'});let created=0,updated=0,failed=0;for(const row of rows){try{const number=clean(row.asset_number||row.assetNumber,30),name=clean(row.name,160);if(!number||!name){failed++;continue}const r=await pool.query(`INSERT INTO assets(asset_number,name,type,owner,state,serial_number,model,site,supplier,cost_centre) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT(asset_number) DO UPDATE SET name=EXCLUDED.name,type=EXCLUDED.type,owner=EXCLUDED.owner,state=EXCLUDED.state,serial_number=EXCLUDED.serial_number,model=EXCLUDED.model,site=EXCLUDED.site,supplier=EXCLUDED.supplier,cost_centre=EXCLUDED.cost_centre,updated_at=NOW() RETURNING (xmax=0) inserted`,[number,name,clean(row.type,80)||'Other',clean(row.owner,120),clean(row.state,40)||'Operational',clean(row.serial_number||row.serialNumber,160),clean(row.model,160),clean(row.site,120),clean(row.supplier,200),clean(row.cost_centre||row.costCentre,120)]);r.rows[0].inserted?created++:updated++}catch{failed++}}res.json({created,updated,failed,total:rows.length})}catch(e){next(e)}});
 app.get('/api/cmdb/export.csv',async(_req:any,res:any,next:any)=>{try{const rows=(await pool.query(`SELECT asset_number,name,type,state,lifecycle_state,stock_status,site,owner,serial_number,model,supplier,cost_centre,purchase_date,purchase_cost,currency,warranty_end,data_quality_score FROM assets ORDER BY asset_number`)).rows,keys=Object.keys(rows[0]||{asset_number:'',name:''});const csv=[keys.join(','),...rows.map((r:any)=>keys.map(k=>`"${String(r[k]??'').replace(/"/g,'""')}"`).join(','))].join('\r\n');res.type('text/csv').setHeader('Content-Disposition','attachment; filename="coreops-cmdb.csv"');res.send(csv)}catch(e){next(e)}});
}
