import type {Express} from 'express';
type Roles=(...roles:any[])=>any;
const text=(v:any,n=2000)=>String(v??'').trim().slice(0,n);
export async function ensurePhase7V29(pool:any){await pool.query(`
 CREATE TABLE IF NOT EXISTS business_services(id BIGSERIAL PRIMARY KEY,code VARCHAR(50) UNIQUE NOT NULL,name TEXT NOT NULL,description TEXT DEFAULT '',owner TEXT DEFAULT '',technical_owner TEXT DEFAULT '',criticality VARCHAR(20) DEFAULT 'Medium',status VARCHAR(30) DEFAULT 'Operational',target_availability NUMERIC(5,2) DEFAULT 99.90,site_id INTEGER REFERENCES sites(id) ON DELETE SET NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
 CREATE TABLE IF NOT EXISTS service_assets(service_id BIGINT NOT NULL REFERENCES business_services(id) ON DELETE CASCADE,asset_id INTEGER NOT NULL REFERENCES assets(id) ON DELETE CASCADE,relationship_type VARCHAR(40) DEFAULT 'Supports',PRIMARY KEY(service_id,asset_id));
 CREATE TABLE IF NOT EXISTS service_feedback(id BIGSERIAL PRIMARY KEY,record_type VARCHAR(30) NOT NULL,record_id TEXT NOT NULL,rating INTEGER NOT NULL CHECK(rating BETWEEN 1 AND 5),comment TEXT DEFAULT '',submitted_by TEXT DEFAULT '',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),UNIQUE(record_type,record_id,submitted_by));
 CREATE TABLE IF NOT EXISTS service_status_updates(id BIGSERIAL PRIMARY KEY,service_id BIGINT NOT NULL REFERENCES business_services(id) ON DELETE CASCADE,status VARCHAR(30) NOT NULL,message TEXT NOT NULL,starts_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),ends_at TIMESTAMPTZ,created_by TEXT DEFAULT '',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
 INSERT INTO business_services(code,name,description,owner,technical_owner,criticality) VALUES('CORE-OPS','Core Ops Workflow','Enterprise service, infrastructure and compliance operations.','Operations','Infrastructure','High') ON CONFLICT(code) DO NOTHING;
 INSERT INTO schema_migrations(migration_key,description) VALUES('029-phase7','Service portfolio and experience') ON CONFLICT(migration_key) DO NOTHING;
`)}
export function registerPhase7V29(app:Express,pool:any,requireRoles:Roles){const write=requireRoles('Administrator','Service Desk','Engineer','Infrastructure'),admin=requireRoles('Administrator');
 app.get('/api/services',async(_req:any,res:any,next:any)=>{try{res.json((await pool.query(`SELECT s.*,COUNT(DISTINCT sa.asset_id)::int asset_count,COUNT(DISTINCT i.id) FILTER(WHERE i.status NOT IN ('Resolved','Closed'))::int open_incidents FROM business_services s LEFT JOIN service_assets sa ON sa.service_id=s.id LEFT JOIN assets a ON a.id=sa.asset_id LEFT JOIN incidents i ON i.asset IN (a.asset_number,a.name) GROUP BY s.id ORDER BY s.criticality,s.name`)).rows)}catch(e){next(e)}});
 app.post('/api/services',admin,async(req:any,res:any,next:any)=>{try{const b=req.body||{};const r=await pool.query(`INSERT INTO business_services(code,name,description,owner,technical_owner,criticality,status,target_availability,site_id) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,[text(b.code,50).toUpperCase(),text(b.name,300),text(b.description),text(b.owner),text(b.technicalOwner),text(b.criticality,20)||'Medium',text(b.status,30)||'Operational',Number(b.targetAvailability||99.9),b.siteId||null]);res.status(201).json(r.rows[0])}catch(e){next(e)}});
 app.get('/api/services/:id/detail',async(req:any,res:any,next:any)=>{try{const service=(await pool.query('SELECT * FROM business_services WHERE id=$1',[req.params.id])).rows[0];if(!service)return res.status(404).json({error:'service not found'});const [assets,updates]=await Promise.all([pool.query(`SELECT a.asset_number,a.name,a.type,a.state,sa.relationship_type FROM service_assets sa JOIN assets a ON a.id=sa.asset_id WHERE sa.service_id=$1 ORDER BY a.name`,[req.params.id]),pool.query(`SELECT * FROM service_status_updates WHERE service_id=$1 ORDER BY starts_at DESC LIMIT 50`,[req.params.id])]);res.json({service,assets:assets.rows,updates:updates.rows})}catch(e){next(e)}});
 app.post('/api/services/:id/assets',write,async(req:any,res:any,next:any)=>{try{const a=(await pool.query('SELECT id FROM assets WHERE asset_number=$1 OR id::text=$1',[String(req.body?.assetId)])).rows[0];if(!a)return res.status(404).json({error:'asset not found'});await pool.query(`INSERT INTO service_assets(service_id,asset_id,relationship_type) VALUES($1,$2,$3) ON CONFLICT(service_id,asset_id) DO UPDATE SET relationship_type=EXCLUDED.relationship_type`,[req.params.id,a.id,text(req.body?.relationshipType,40)||'Supports']);res.status(201).json({ok:true})}catch(e){next(e)}});
 app.post('/api/services/:id/status',write,async(req:any,res:any,next:any)=>{try{const b=req.body||{},status=text(b.status,30);const r=await pool.query(`INSERT INTO service_status_updates(service_id,status,message,ends_at,created_by) VALUES($1,$2,$3,$4,$5) RETURNING *`,[req.params.id,status,text(b.message),b.endsAt||null,req.authUser?.email||'']);await pool.query('UPDATE business_services SET status=$1,updated_at=NOW() WHERE id=$2',[status,req.params.id]);res.status(201).json(r.rows[0])}catch(e){next(e)}});
 app.get('/api/portal/my-requests',async(req:any,res:any,next:any)=>{try{const keys=[req.authUser?.name||'',req.authUser?.email||''];res.json((await pool.query(`SELECT r.*,c.name catalogue_name,(SELECT ROUND(AVG(f.rating),1) FROM service_feedback f WHERE f.record_type='Request' AND f.record_id=r.number) rating FROM service_requests r LEFT JOIN service_catalogue_items c ON c.id=r.catalogue_item_id WHERE r.requested_for=ANY($1::text[]) ORDER BY r.created_at DESC LIMIT 200`,[keys])).rows)}catch(e){next(e)}});
 app.post('/api/feedback',async(req:any,res:any,next:any)=>{try{const b=req.body||{},rating=Number(b.rating);if(!['Incident','Request'].includes(String(b.recordType))||!text(b.recordId,80)||rating<1||rating>5)return res.status(400).json({error:'valid record and rating required'});const r=await pool.query(`INSERT INTO service_feedback(record_type,record_id,rating,comment,submitted_by) VALUES($1,$2,$3,$4,$5) ON CONFLICT(record_type,record_id,submitted_by) DO UPDATE SET rating=EXCLUDED.rating,comment=EXCLUDED.comment RETURNING *`,[b.recordType,text(b.recordId,80),rating,text(b.comment),req.authUser?.email||req.authUser?.name||'']);res.status(201).json(r.rows[0])}catch(e){next(e)}});
 app.get('/api/reporting/experience',async(_req:any,res:any,next:any)=>{try{const r=await pool.query(`SELECT (SELECT COUNT(*) FROM business_services)::int services,(SELECT COUNT(*) FROM business_services WHERE status<>'Operational')::int degraded_services,(SELECT ROUND(AVG(rating),2) FROM service_feedback) average_rating,(SELECT COUNT(*) FROM service_feedback)::int responses,(SELECT COUNT(*) FROM service_requests WHERE created_at>NOW()-INTERVAL '30 days')::int requests_30d,(SELECT COUNT(*) FROM service_requests WHERE status='Fulfilled' AND completed_at>NOW()-INTERVAL '30 days')::int fulfilled_30d`);res.json({...r.rows[0],generatedAt:new Date().toISOString()})}catch(e){next(e)}});
}
